frontend/src/app/AddManagedCluster/AddManagedCluster.tsx
frontend/src/app/routes.tsx

Hello! :hugs: 
This is a WIP PR in regards to solve issue #11.
For now, this pull request is in work in progress, and handles a UI that gives a very basic idea of how the front end for Add Managed Cluster would look like!

Adds a page for Add Managed Cluster Area (Solves #11) 

---

.gitleaks.toml
backend/Dockerfile
backend/Makefile
manifests/postgresql-staging/postgresql-staging.yaml
manifests/postgresql-staging/values.yaml
manifests/services/application/deployment.yaml
manifests/services/application/deplyoment.yaml
manifests/services/application/kustomization.yaml
manifests/services/application/routes.yaml
manifests/services/application/service.yaml

Hello! :hugs:
This is a PR in regards to solving issue [GITOPS-1380](https://issues.redhat.com/browse/GITOPS-1380). The PR consists of following changes:
- Adds a Dockerfile
- 'make image' and 'make image-push' target to the Makefile
- Adds K8s resources (Deployment, Service, Route) 
- Adds K8s resources for development postgresql

Adds Dockerfile and K8s resources for gitops-backend service and RDBMS (Solves: Gitops-1380)

---

cluster-agent/controllers/managed-gitops/operation_controller.go
cluster-agent/controllers/managed-gitops/suite_test.go
cluster-agent/go.mod
cluster-agent/go.sum
cluster-agent/main.go
cluster-agent/utils/retrieve_metrics.go

Hello! :hugs:
This PR is in regards to solving the issue [GITOPS-1389](https://issues.redhat.com/browse/GITOPS-1389).

Adds initial support for retrieving metrics from an Argo CD instance (Solves: Gitops-1389)

---

backend-shared/config/db/application.go
backend-shared/config/db/clusteraccess.go
backend-shared/config/db/clustercredentials.go
backend-shared/config/db/clusteruser.go
backend-shared/config/db/deploymenttoapplicationmapping.go
backend-shared/config/db/gitopsenginecluster.go
backend-shared/config/db/gitopsengineinstance.go
backend-shared/config/db/managedenvironment.go
backend-shared/config/db/queries.go
backend-shared/config/db/types.go
backend-shared/config/db/types_test.go
backend-shared/config/db/utils.go
db-schema.sql

Part of https://issues.redhat.com/browse/GITOPS-1457

Add Deployment to Application Mapping, fix schema, add new DB queries

---

backend-shared/config/db/application.go
backend-shared/config/db/applicationstates.go
backend-shared/config/db/clusteraccess.go
backend-shared/config/db/clustercredentials.go
backend-shared/config/db/clusteruser.go
backend-shared/config/db/deploymenttoapplicationmapping.go
backend-shared/config/db/gitopsenginecluster.go
backend-shared/config/db/gitopsengineinstance.go
backend-shared/config/db/kubernetesresourcetodbresourcemapping.go
backend-shared/config/db/managedenvironment.go
backend-shared/config/db/operations.go
backend-shared/config/db/queries.go
backend-shared/config/db/types.go
backend-shared/config/db/types_test.go
backend-shared/config/db/utils.go
db-schema.sql

This PR:
- Update database APIs, and switches existing code to use those APIs
- Cleans up existing database code
- Add KubernetesToDBResourceMapping table

Update database APIs, cleanup existing code, add KubernetesToDBResourceMapping table

---

.codecov.yml

Roughly based on https://github.com/argoproj/argo-cd/blob/master/.codecov.yml
Mainly I created this to get rid of the annotations on GitHub PRs :stuck_out_tongue:

Add codecov YAML file

---

backend-shared/config/db/types_test.go
backend-shared/util/utils_test.go
db-schema.sql

Hi :hugs:
This pull request is in with regards to the story GitOps-1461, the story deals with adding foreign keys to database schema and fixing tests accordingly!

Add foreign keys to databases and fix tests (Solves: GitOps-1461)

---

backend-shared/config/db/injection_test.go

Hi :hugs:
This pull request is in with regards to story GITOPS-1375, which checks for inputting malicious values within the database objects!

Add tests to check the sanity for the database input methods

---

backend-shared/config/db/application.go
backend-shared/config/db/applicationstates.go
backend-shared/config/db/deploymenttoapplicationmapping.go
backend-shared/config/db/queries.go
backend-shared/config/db/types.go
cluster-agent/controllers/argoproj.io/application_controller.go
cluster-agent/go.mod
cluster-agent/go.sum

Hi :hugs:
This pull request is in with regards to story GITOPS-1378, it consists of relevant Unsafe (create/update) function in for Application and ApplicationState. Along with update in reconciler function which is responsible for checking the following:
- If the entry exists at neither place, do nothing
- if the entry exists in the database but not in the namespace, create application in  the namespace
- if the entry exists not in the database but in the namespace, delete application from the namespace
- if exists at both places, then compare and update the changes in the namespace
This PR is in under WIP right now!

Database Integration to Cluster Agent (Solves: GITOPS-1378)

---

utilities/load-test/loadtest/loadtest_test.go
utilities/load-test/loadtest/utility.go

Hi, :hugs:! 
This is a draft PR for ArgoCD LoadTest [GITOPS-1508](https://issues.redhat.com/browse/GITOPS-1508), which adds a test for testing n applications with non-pod based resources. The repository that contains those manifests lies here for [now](https://github.com/samyak-jn/gitops-service-sample-k8s-resources).

Add ArgoCD Load Test part-2 (Solves: GITOPS-1508)

---

examples/m2-demo/README.md
examples/m2-demo/jane-deployment.yaml
examples/m2-demo/jgw-deployment.yaml
examples/m2-demo/k8s/README.md
examples/m2-demo/k8s/jane-deployment.yaml
examples/m2-demo/k8s/jgw-deployment.yaml
examples/m2-demo/setup-on-openshift.sh

This PR adds setup scripts, GitOpsDeployment API examples, and instructions, for running the demo.

Add M2 demo install instructions, and steps

---

backend-shared/util/task_retry_loop.go

This PR:
- Adds description to the task retry loop, and struct comment
- Fixes a magic number that should be using the existing constant value

Add comment description to task retry loop

---

appstudio-controller/go.sum
backend-shared/config/db/ephemeralPostgres.go
backend-shared/config/db/ephemeralPostgres_test.go
backend-shared/go.mod
backend-shared/go.sum
backend-shared/hack/service_account_test.go
backend-shared/util/task_retry_loop.go
backend-shared/util/test_task_retry_loop_test.go
backend-shared/util/util_suite_test.go
backend/go.sum

This PR consists of Unit Tests for the Task Retry Loop as described in [https://issues.redhat.com/browse/GITOPSRVCE-111](https://issues.redhat.com/browse/GITOPSRVCE-111)

Unit tests for the task retry loop

---

.github/pull_request_template.md
.github/workflows/static.yml
Makefile

- Add a simple PR template
- Update go-fmt check

Update go-fmt check and add simple PR template

---

backend/eventloop/workspace_event_loop_test.go

This PR will add more unit test cases for `backend/eventloop/workspace_event_loop.go`
https://issues.redhat.com/browse/GITOPSRVCE-113

Unit tests for WorkspaceEventLoop.

---

Makefile
argocd.sh

There is no related JIRA ticket for this.
I think it's useful for some quick verification locally and for demo purposes.
Think of it as a bonus/optional functionality provided by the Makefile.

Add Makefile ArgoCD upstream deployment

---

.tekton/pull-request.yaml

- Remove service account name based on comment [here](https://github.com/redhat-appstudio/managed-gitops/pull/93#discussion_r847442953)

Remove Service account name

---

backend-shared/config/db/deploymenttoapplicationmapping.go
backend-shared/config/db/deploymenttoapplicationmapping_test.go
backend-shared/config/db/queries.go
backend-shared/config/db/types.go
backend-shared/config/db/util/utils.go
backend/apis/managed-gitops/v1alpha1/gitopsdeployment_types.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
db-schema.sql

This PR mainly adds a bunch of comments to the code, plus a couple of very minor code tweaks.
- Updates to comments in various parts of the code:
- Add health codes, update event runner comments
- Add more comments to application event runner deployments handler
- Add additional comments to DB schema, and clean up queries interface
- Add additional DB comments and cleanup
- Add more explanatory comments to `utils.go` in `backend-shared`
- Add additional comments to shared resource loop
- Minor code tweaks
- Update DeploymentToApplicationMapping field from WorkspaceUID -> NamespaceUID
- Remove an unnecessary else block in `GetGitopsEngineClusterByKubeSystemNamespaceUID`

Add explanatory comments to various code, plus minor tweaks

---

manifests/managed-gitops-appstudio-controller-deployment.yaml
manifests/managed-gitops-backend-deployment.yaml
manifests/managed-gitops-clusteragent-deployment.yaml

- Increase the resource limits on the controllers, when running on appstudio staging cluster

Update memory/cpu req/limits for components in K8s resource manifests

---

backend-shared/config/db/util/application_info_cache.go
backend-shared/config/db/util/application_info_cache_test.go
backend-shared/config/db/utils.go
cluster-agent/controllers/argoproj.io/application_controller.go
cluster-agent/controllers/argoproj.io/application_controller_suite_test.go
cluster-agent/controllers/argoproj.io/application_controller_test.go
cluster-agent/go.mod
cluster-agent/go.sum
cluster-agent/main.go

Description:
- Unit test cases for application controller in cluster agent using ginkgo.
JIRA Story : https://issues.redhat.com/browse/GITOPSRVCE-116

Write unit test cases for application controller in cluster-agent #116

---

backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go

This PR will enhance unit tests for Application Event Runner loop and address few missing test scenarios.
https://issues.redhat.com/browse/GITOPSRVCE-128
1. Modified function signature in `application_event_runner_deployments` to inform the caller that what type of operation was performed on gitOpsDeloyment object (i.e Create, Update, Error).
2. Added few more tests cases in `application_event_runner_test`
3. Added a new entry in `DbFieldMap` of `backend-shared/config/db/db_field_constants.go` to fix unit test failure due to renaming of a field in `PR 101`

Enhance tests for Application Event Runner.

---

backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go

This PR is adding unit tests to cover `applicationEventRunner_handleUpdateDeploymentStatusTick` function of `applicationEventRunner`.
https://issues.redhat.com/browse/GITOPSRVCE-127

Add more unit tests for ApplicationEventRunner.

---

.gitleaks.toml

- Update `.gitleaks.toml` to make Red Hat scanner happy
- Add description of how to verify the scan is correct
- Add extra comments on how to ignore individual files.

Update .gitleaks.toml with known safe passwords

---

backend-shared/config/db/util/utils_test.go

This PR is to address few review comments left in https://github.com/redhat-appstudio/managed-gitops/pull/117

Modify unit test for utility functions of backend-shared/config/db

---

.github/workflows/static.yml
Makefile
appstudio-controller/Makefile
appstudio-controller/controllers/appstudio.redhat.com/applicationpromotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/applicationsnapshotenvironmentbinding_controller.go
appstudio-shared/Makefile
appstudio-shared/apis/appstudio.redhat.com/v1alpha1/applicationpromotionrun_types.go
appstudio-shared/apis/appstudio.redhat.com/v1alpha1/applicationsnapshot_types.go
appstudio-shared/config/crd/bases/appstudio.redhat.com_applicationpromotionruns.yaml
appstudio-shared/config/crd/bases/appstudio.redhat.com_applicationsnapshots.yaml
appstudio-shared/manifests/appstudio-shared-customresourcedefinitions.yaml
backend-shared/Makefile
backend/Makefile
cluster-agent/Makefile
tests-e2e/Makefile
utilities/db-migration/Makefile

- Add 'proof-of-concept' code for the Environments API, specificially for Binding and PromotionRun resources, for story owners to complete as part of GITOPSRVCE-156/157.
- The Go code is me brainstorming the reconcile logic for how these stories will work, but in Go form (rather than in a Google doc). Story owners should feel free to rip apart the logic as needed :smile:.
- https://issues.redhat.com/browse/GITOPSRVCE-156
- https://issues.redhat.com/browse/GITOPSRVCE-157

Add proof-of-concept code for Environments API for GITOPSRVCE-156/157

---

backend-shared/config/db/application.go
backend-shared/config/db/application_test.go
backend-shared/config/db/clusteruser.go
backend-shared/config/db/clusteruser_test.go
backend-shared/config/db/queries.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
cluster-agent/controllers/argoproj.io/application_controller.go
cluster-agent/controllers/argoproj.io/application_controller_test.go
cluster-agent/go.mod
cluster-agent/go.sum
cluster-agent/main.go
tests-e2e/go.mod

This PR is to add a function into Cluster Agent which iterates through each Workspace/Namespace present in DB after a fixed interval and ensures that the state of resources (Applications) in Cluster is in Sync with DB.
https://issues.redhat.com/browse/GITOPSRVCE-57

Periodic Reconciliation of Workspaces/Namespaces.

---

create-dev-env.sh

- Fixes a OpenShift CI failure that is being seen on PRs.
- Switches to using the migration logic to initialize the database scheme when running on k8s, similar to what we are doing in all other cases (docker devenv, staging cluster)
- Increase timeouts to make sure we wait long enough for PostgreSQL to come up

Fix CI: Switch to using migration to initialize the database scheme when running on k8s, increase timeouts

---

manifests/appstudio-controller-rbac/appstudio-controller-rbac.yaml

- Update the appstudio-controller role to include the latest Environment APIs

Update appstudio controller RBAC to add Environment API

---

OWNERS

As per our previous discussions, This should be a quick merge to add @chetan-rns to the list of reviewers which is used by openshift-ci!
Welcome to the team, @chetan-rns ! :taco: :rocket: :heart:

Add chetan to the list of reviewers for the openshift-ci

---

manifests/managed-gitops-appstudio-controller-deployment.yaml
manifests/managed-gitops-backend-deployment.yaml
manifests/managed-gitops-clusteragent-deployment.yaml

- Update health ports so they are consistent with what port the controller is actually listening on, to fix health check issues.
- Add zap time encoding parameter, to improve the time reporting format of the controller when running on staging cluster

Update manifests: update health ports, and add zap logging parameter

---

backend-shared/util/service_account.go
backend-shared/util/service_account_test.go

- From k8s 1.24 onwards service accounts will not get a default token secret. Instead, we need to create a token secret of type `kubernetes.io/service-account-token` and point it to our service account. 
- Add unit test to check the above behavior
https://issues.redhat.com/browse/GITOPSRVCE-171

Create a new token secret for service account if the default secret is absent

---

.github/workflows/static.yml
Makefile
tests-e2e/go.mod
tests-e2e/go.sum
utilities/db-migration/migrate/migrate_db.go
utilities/db-migration/migrations/000003_v3.down.sql
utilities/verify-db-migration.sh

- Adds a CI task and a shell script to verify if newly added migrations are working as expected and don't lead to dirty migrations.

CI task for testing the down migrations of our database migrations

---

tests-e2e/core/core_suite_test.go
tests-e2e/core/gitopsDeployment_test.go
tests-e2e/core/simple_test.go
tests-e2e/fixture/fixture.go
tests-e2e/fixture/gitopsdeployment/fixture.go
tests-e2e/fixture/k8s/fixture.go
tests-e2e/go.sum
utilities/db-migration/go.mod
utilities/db-migration/go.sum

This PR contains e2e test for GitOpsDeployment API
https://issues.redhat.com/browse/GITOPSRVCE-154

E2e test for GitOpsDeployment API

---

argocd.sh

- Argo CD namespace should be read from the variable `ARGO_CD_NAMESPACE`
- The port used for port-forwarding is already used by backend metrics. Use a different port number 4000

Fix argocd installation script to use the correct namespace and port

---

manifests/managed-gitops-appstudio-controller-deployment.yaml
manifests/managed-gitops-backend-deployment.yaml

- Increase the liveness/readiness probe duration of backend
- Increase the memory limit of appstudio-controller

Update backend/appstudio-controller K8s manifests

---

manifests/managed-gitops-appstudio-controller-deployment.yaml

fix: type 256i -> 256Mi

---

manifests/managed-gitops-backend-deployment.yaml

- Increase memory limit of backend controller

Increase memory limit of backend controller

---

.github/workflows/static.yml
backend/eventloop/application_event_loop/application_event_runner_deployments.go

- Add check for duplicate packages
No

Add CI checks for duplicate pkg

---

cluster-agent/controllers/managed-gitops/eventloop/repocred_test.go

- Changing from `dbq.CreateOperation()` into `operations.CreateOperation()`. The first one creates only the DB Row, while the second one it goes on step further and creates also the corresponding CR in the cluster.
REF: https://issues.redhat.com/browse/GITOPSRVCE-96

Refactor repocred tests to use operations.CreateOperation()

---

appstudio-controller/config/manager/manager.yaml
appstudio-shared/config/manager/manager.yaml
backend/config/manager/manager.yaml
manifests/backend-rbac/managed-gitops-backend-manager-role.yaml
manifests/cluster-agent-rbac/managed-gitops-clusteragent-manager-role.yaml
manifests/managed-gitops-appstudio-controller-deployment.yaml
manifests/managed-gitops-backend-deployment.yaml
manifests/managed-gitops-clusteragent-deployment.yaml

- This PR includes having a basic review of the operator security guidelines and making sure that the operator follows best practices for operator security and has a secured operator deployment.
- This [document](https://docs.google.com/document/d/1yv9QKw4uYWbhAmrqyPA0ZQYqkRmcFRyIkOnEjRpTVpU/edit) is a brief gist of the review conducted over the relevant manifests and includes what are the basic security guidelines we need to look for.

Review Operator security guidelines and review k8s resources (Solves: #GITOPSRVCE-185)

---

kcp/ckcp/setup-ckcp-on-openshift.sh

- It is being observed that while in openshift-ci testing, it starts to port-forward before the Postgres pod is in the Running state; hence, to resolve this, added a check for postgres pod to be in running status if the port is being occupied and finally if the port-forwarding is working, thanks to the create-dev-env script.
Log for ref:

Add a check for postgres pod running and port-forwarding status for CI

---

kcp/ckcp/setup-ckcp-on-openshift.sh

- Tested changes on ci, including proper export of kubeconfig and finally :green_circle: (YAY!)
- Needed to merge these changes to main, to finalize the story

Enable ci kcp based (merge to main, tested changes)

---

tests-e2e/core/applicationpromotionrun_controller_test.go

This PR is to fix an issue with one of the PromotionRun E2E tests.
https://issues.redhat.com/browse/GITOPSRVCE-234

Fix PromotionRun E2E test.

---

appstudio-controller/controllers/appstudio.redhat.com/applicationsnapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/applicationsnapshotenvironmentbinding_controller_test.go
tests-e2e/core/applicationsnapshotenvironmentbinding_test.go

- Append ApplicationSnapshotEnvironmentBindingResource labels with prefix appstudio.openshift.io to GitopsDeployment labels
https://issues.redhat.com/browse/GITOPSRVCE-222

Append ASEB labels to GitopsDeployment labels

---

appstudio-controller/controllers/appstudio.redhat.com/application_controller.go

- Moved code logic of creating GitopsDeployment from Reconcile function of application_controller.go to a new function called gitopsDeploymentCreation
-  gitopsDeploymentCreation  function is not called anywhere
- Added `nolint` comment to avoid lint error
https://issues.redhat.com/browse/GITOPSRVCE-215

Disable appstudio logic which create a GitOpsDeployment for every AppStudio Application

---

backend-shared/util/service_account.go

Fix serviceaccount test by searching token based on annotations. This allows test to run on `kind` or `k3s` as the implementation of token links with service account is different.

Fix serviceaccount test by searching token based on annotations

---

Makefile
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-shared/config/kcp/apiexport_gitopsrvc_appstudioshared.yaml
appstudio-shared/config/kcp/apiresourceschema_gitopsrvc_appstudioshared.yaml
backend-shared/util/manager.go
backend/eventloop/application_event_loop/application_event_loop.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/application_event_loop/metrics_test.go
backend/eventloop/eventlooptypes/types.go
backend/eventloop/eventlooptypes/types_suite_test.go
backend/eventloop/eventlooptypes/types_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
cluster-agent/Makefile
kcp/utils.sh
kcp/virtual-workspace.sh

- Update Makefile to install Argo CD and cluster-agent in the workload cluster
- Generate credentials for accessing the workload cluster
- Update APIResourceSchemas for Appstudio CRDs
- Use a different client for GitOpsEngine/workload cluster.
https://issues.redhat.com/browse/GITOPSRVCE-237

Support running Argo CD/cluster-agent on workload cluster

---

tests-e2e/core/gitopsdeployment_status_test.go
tests-e2e/core/gitopsdeployment_test.go
tests-e2e/core/snapshotenvironmentbinding_test.go
tests-e2e/fixture/gitopsdeployment/fixture.go

- Fixed e2e tests which are failing

Fix e2e tests which are failing

---

kcp/ckcp/config.yaml
kcp/ckcp/openshift_dev_setup.sh
kcp/ckcp/setup-ckcp-on-openshift.sh

- Fix the KCP E2E CI by fixing CKCP issues

Fix the KCP E2E CI by fixing CKCP issues (Solves: #GITOPSRVCE-252)

---

openshift-ci/build-root/Dockerfile

Changes for OpenShift-CI.

---

manifests/controller-deployments/managed-gitops-backend-deployment.yaml

- Update backend service resource limit for appstudio controller

Update backend service resource limit for appstudio controller

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentmanagedenvironment_types.go
backend-shared/config/crd/bases/managed-gitops.redhat.com_gitopsdeploymentmanagedenvironments.yaml
backend-shared/config/db/db_field_constants.go
backend-shared/config/db/types.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
cluster-agent/utils/argocd_login_command.go
db-schema.sql
tests-e2e/core/managed_environment_test.go
utilities/db-migration/migrations/000009_v9.down.sql
utilities/db-migration/migrations/000009_v9.up.sql

Allow user to opt-in to supporting insecure remote clusters with GitOpsDeploymentManagedEnvironment
https://issues.redhat.com/browse/GITOPSRVCE-178

Enable TLS certificate validation for insecure remote clusters

---

appstudio-controller/config/rbac/role.yaml
appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
manifests/appstudio-controller-rbac/appstudio-controller-rbac.yaml

- Add missing RBAC tags, and regenerate role.yaml
- Update the standalone appstudio RBAC yaml (which will be deprecated soon by another story)

Add ManagedEnvironments to appstudio-controller-rbac, update RBAC missing tags

---

appstudio-controller/controllers/appstudio.redhat.com/application_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
backend-shared/util/chaosclient.go
backend-shared/util/manager.go
backend-shared/util/service_account.go
backend/controllers/managed-gitops/gitopsdeployment_controller.go
backend/controllers/managed-gitops/gitopsdeploymentmanagedenvironment_controller.go
backend/controllers/managed-gitops/gitopsdeploymentrepositorycredential_controller.go
backend/controllers/managed-gitops/gitopsdeploymentsyncrun_controller.go
backend/eventloop/eventlooptypes/types.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
cluster-agent/controllers/argoproj.io/application_controller.go
cluster-agent/controllers/managed-gitops/operation_controller.go

- Create a simulated unreliable K8s client
https://issues.redhat.com/browse/GITOPSRVCE-284

Chaos Engineering: Create a simulated unreliable K8s client

---

tests-e2e/core/gitopsdeployment_syncrun_test.go
tests-e2e/fixture/application/fixture.go

- e2e test for GitOpsDeploymentSyncRun API
https://issues.redhat.com/browse/GITOPSRVCE-153

Add e2e test for GitOpsDeploymentSyncRun API

---

utilities/db-migration/go.mod
utilities/db-migration/main.go

- (Provide a brief list of the changes you have made, and why you made those changes, if it is not obvious why)

update module name in db-migration

---

backend/go.mod
backend/go.sum
backend/main.go

- (Provide a brief list of the changes you have made, and why you made those changes, if it is not obvious why)

update backend deps

---

docs/bump_argocd.md

-  Provide documentation for bumping ArgoCD version in the repo
Action Item from Retrospective
https://issues.redhat.com/browse/GITOPSRVCE-332

Add docs for ArgoCD bump

---

OWNERS

- Update OWNERs file with latest changes

Update OWNERs file

---

tests-e2e/fixture/fixture.go

Add code to the e2e test cleanup code to delete application, environment and snapshot environment binding resources before deleting gitops service resources, since the former are likely owners of the latter and so should be deleted first.

Delete top-level resources first as part of e2e cleanup

---

backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/application_event_loop/application_event_runner_syncruns_test.go
backend/eventloop/application_event_loop/application_event_runner_test.go

- Return an error when a user tries to sync a GitOpsDeployment with the 'Automated' sync policy
- Unit test
https://issues.redhat.com/browse/GITOPSRVCE-336

Validate syncing with Automated sync policy

---

backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/application_event_loop/application_event_runner_syncruns_test.go
tests-e2e/core/gitopsdeployment_syncrun_test.go
tests-e2e/fixture/gitopsdeploymentsyncrun/fixture.go

- Set conditions based on the errors received while handling GitOpsDeploymentSyncRun
- Include unit tests
https://issues.redhat.com/browse/GITOPSRVCE-44

Report errors to GitOpsDeploymentSyncRun status conditions

---

Makefile
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
appstudio-controller/go.mod
appstudio-controller/go.sum
tests-e2e/core/snapshotenvironmentbinding_test.go
tests-e2e/fixture/binding/fixture.go
tests-e2e/fixture/gitopsdeployment/fixture.go
tests-e2e/go.mod
tests-e2e/go.sum

- Updated the reconciler for SnapshotEnvironmentBinding to add a condition indicating if all components have been deployed.
- Added unit tests
- Added end-to-end tests

Add SnapshotEnvironmentBinding deployment status condition

---

.tekton/push.yaml

- The infra-deployments repository uses this value to determine how to update the repository with new container images/commits, [for example](https://github.com/redhat-appstudio/infra-deployments/pull/1108/files)

Update push.yaml to support new kustomize repository URL format

---

tests-e2e/core/gitopsdeployment_test.go
tests-e2e/fixture/gitopsdeployment/fixture.go
utilities/db-migration/go.mod
utilities/db-migration/go.sum

- Simulates GitopsDeployment for simple interactions of X active users interacting with the service
https://issues.redhat.com/browse/GITOPSRVCE-172

 E2E test that simulates simple interactions of X active users interacting with the service

---

cluster-agent/controllers/util.go
cluster-agent/controllers/util_test.go

- Changes to couple of files seem to have been missed for PR #301.  This PR updates those files.

Fix changes missed in db folder move

---

backend-shared/util/operations/types.go
backend-shared/util/operations/types_test.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
cluster-agent/controllers/argoproj.io/namespace_reconciler.go

- Fix the CleanupOperation() in backend-shared
- Add/Fix unit tests
https://issues.redhat.com/browse/GITOPSRVCE-290

Refactor CleanupOperation in backend-shared

---

appstudio-controller/go.mod
backend/go.mod
backend/go.sum
cluster-agent/go.mod

- (Provide a brief list of the changes you have made, and why you made those changes, if it is not obvious why)

upgrade db-migrate in backend

---

backend-shared/db/gitopsengineinstance.go
backend-shared/db/gitopsengineinstance_test.go
backend-shared/db/queries.go
cluster-agent/controllers/argoproj.io/namespace_reconciler.go
cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go

This PR is to add logic to look for orphan secrets in cluster and delete them periodically. 
https://issues.redhat.com/browse/GITOPSRVCE-349

Periodic job to clean up orphan secrets from cluster.

---

backend-shared/db/queries.go
backend-shared/db/unreliable_db_client.go

Created new file in backend-shared/db called unreliable_db_client.go and created a new struct chaosDBClient to implement all the functions of DatabaseQueries
https://issues.redhat.com/browse/GITOPSRVCE-331

Simulate an unreliable database by randomly injecting errors 

---

Makefile

- Target for running lint checks for all components

Add Makefile target to run lint checks for all components

---

appstudio-controller/config/rbac/role.yaml
appstudio-controller/controllers/appstudio.redhat.com/application_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go

- appstudio-controller requires access to the Namespace K8s resource, and is currently failing due to this lack of access

Add Namepaces to appstudio-controller role

---

manifests-v1/postgresql-staging/README.md
manifests-v1/postgresql-staging/postgresql-staging.yaml
manifests/base/postgresql-staging/README.md
manifests/base/postgresql-staging/postgresql-staging.yaml

- Update the PostgreSQL image version to match the version in RDS

Update PostgreSQL version

---

.github/workflows/static.yml
utilities/db-migration/go.mod
utilities/db-migration/migrate/migrate_db.go
utilities/db-migration/migration_test/add_test_values/add_db_values.go
utilities/db-migration/migration_test/add_test_values/add_db_values_test.go
utilities/db-migration/migration_test/add_test_values/suite_test.go
utilities/db-migration/migration_test/verify_test_values/suite_test.go
utilities/db-migration/migration_test/verify_test_values/verify_db_values_test.go

- db-migration tests for adding and verifying data in database
- Added Github CI for db-migration-tests
https://issues.redhat.com/browse/GITOPSRVCE-313

Add db-migration tests to run our database migration tests against live data that represent our actual usage

---

tests-e2e/fixture/gitopsdeployment/fixture.go

- The `UpdateDeploymentWithFunction` fixture function was incorrectly labeled: it was updating the status, rather than the object (spec)
- The test that was calling it was attempting to update the Spec, and likely made an incorrect assumption based on the function name
- This PR adds both status and non-status versions of the function.

Tests-e2e GitOpsDeployment fixture function should update spec, not status

---

.tekton/push.yaml

- update paths in infra-deployments so that pull-request in infra-deployments is created successfully.

tekton-ci: fix paths in infra-deployments

---

backend-shared/db/util/utils.go
backend-shared/db/util/utils_test.go

Signed-off-by: Keith Chong <kykchong@redhat.com>
- Refactor and simplify the logic.
- Two changes related to scope (The use of the curly braces), but it looks like it isn't necessary.  Please confirm.
- Also, I didn't change existing or add any new tests.  They all ran fine.  The various scenarios were not possible anyway.

chore: Cleanup logic in 'GetOrCreateGitOpsEngine*' (#155)

---

manifests/scripts/openshift-argo-deploy/deploy.sh
manifests/scripts/openshift-argo-deploy/openshift-gitops-subscription.yaml

(Provide a brief list of the changes you have made, and why you made those changes, if it is not obvious why)
- I removed/disabled installing the default instance of Argo CD and adjusted the script to not wait for it to complete.
- We don't seem to need it, and we have a copy of the subscription anyway
- After doing this, and configuring the test environment, the tests all ran fine.
- See Jira
Fixes https://issues.redhat.com/browse/GITOPSRVCE-417

Chore: Get dev env working on cluster-bot hypershift (#417)

---

Makefile

- (Provide a brief list of the changes you have made, and why you made those changes, if it is not obvious why)
See Jira for details
See https://issues.redhat.com/browse/GITOPSRVCE-433

Docker build issue on Mac Arm64 (#433)

---

Makefile
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
tests-e2e/core/promotionrun_controller_test.go
tests-e2e/core/snapshotenvironmentbinding_test.go
tests-e2e/fixture/binding/fixture.go

- No new e2e tests were added to test this, but rather, existing e2e tests were modified to take into account the additional fields.
- Please double-check if all the files that are needed to be modified are made when pulling in a new application-api version
See Jira
See https://issues.redhat.com/browse/GITOPSRVCE-199

Add sync/health/commit ID to SnapshotEnvironmentBinding (#199)

---

backend-shared/db/postgres-integration.go

- Don't include DB credentials in the errors because they will be logged.

Don't include DB credentials in the connection err

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go

See details in https://issues.redhat.com/browse/GITOPSRVCE-458
See https://issues.redhat.com/browse/GITOPSRVCE-458

ComponentDeploymentConditions test intermittently failing (#458)

---

manifests/base/monitoring/grafana-dashboards/managed-gitops/gitops-argocd-dashboard.json
manifests/base/monitoring/grafana-dashboards/regenerate-stonesoup-dashboard.sh
manifests/base/monitoring/grafana-dashboards/stonesoup/gitops-argocd-dashboard.json

- Add Argo CD Grafana dashboard for the GitOps Service instance

Add Argo CD Grafana dashboard for the GitOps Service instance

---

appstudio-controller/config/rbac/deploymenttargetclass_view_role.yaml
appstudio-controller/config/rbac/deploymenttargetclass_view_role_binding.yaml
appstudio-controller/config/rbac/kustomization.yaml

- Add read access RBAC to DeployementTargetClass
[https://issues.redhat.com/browse/STONEINTG-351](https://issues.redhat.com/browse/STONEINTG-351)

Add read access Clusterrole(Binding) for CRD DeploymentTargetClass

---

backend-shared/util/service_account.go
backend/eventloop/eventloop_test_util/eventloop_test_util.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
cluster-agent/utils/argocd_create.go
utilities/load-test/loadtest/loadtest_test.go

- Update references from `wait.Poll` to `wait.PollImmediate`. In all cases, they should have been `wait.PollImmediate` to begin with.

chore: Update wait.Poll to wait.PollImmediate

---

backend/config/default-no-prometheus/kustomization.yaml
backend/config/default-no-webhook-no-prometheus/kustomization.yaml
backend/config/default-no-webhook/kustomization.yaml
backend/config/manager/manager.yaml
backend/config/webhook/kustomization.yaml
backend/config/webhook/kustomizeconfig.yaml
backend/config/webhook/manifests.yaml
backend/config/webhook/service.yaml
manifests/overlays/appstudio-staging-cluster/kustomization.yaml
manifests/overlays/k8s-env/kustomization.yaml
manifests/overlays/stonesoup-member-cluster/kustomization.yaml

- Update the backend controller manifests to prepare it for webhook validation, as part [GITOPSRVCE-440](https://issues.redhat.com//browse/GITOPSRVCE-440)

Update backend component to prepare for initial webhook validation support

---

Makefile

Small change to add a reference to an existing test which will be utilised for checking backward compatibility from Openshift CI. 
Relevant PR to Openshift CI to follow once this is merged. 
https://issues.redhat.com/browse/GITOPSRVCE-453

GITOPSSRVCE-453 - Add existing test reference to Makefile 

---

Makefile
Procfile.runexecs
appstudio-controller/.gitignore
appstudio-controller/Makefile
backend/.gitignore
backend/Makefile
cluster-agent/.gitignore
cluster-agent/Makefile

See https://issues.redhat.com/browse/GITOPSRVCE-507
https://issues.redhat.com/browse/GITOPSRVCE-507

Create targets for testing purposes to avoid popups (#507)

---

backend-shared/db/postgres-integration.go
backend-shared/db/queries.go
create-dev-env.sh
docs/debug.md
docs/development.md
manifests-v1/database-init/job.yaml
manifests-v1/postgresql-staging/old-bitnami-yaml/values.yaml
manifests-v1/postgresql-staging/postgresql-staging.yaml
manifests/base/postgresql-staging/postgresql-staging.yaml
psql.sh
utilities/check-db-schema.sh
utilities/db-migration/migrate/migrate_db.go
utilities/verify-db-migration.sh

- Added env var to facilitate customisation of database name which was previously hardcoded to "postgres"
https://issues.redhat.com/browse/GITOPSRVCE-338

Configured Environment Variable to enable customisation of database

---

backend/controllers/managed-gitops/gitopsdeployment_controller.go
backend/controllers/managed-gitops/gitopsdeploymentmanagedenvironment_controller.go
backend/controllers/managed-gitops/gitopsdeploymentrepositorycredential_controller.go
backend/controllers/managed-gitops/gitopsdeploymentsyncrun_controller.go

- Added GenerationChangedPredicate to GitOpsDeployment* controllers

Add GenerationChangedPredicate to GitOpsDeployment* controllers

---

appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
appstudio-controller/go.mod
appstudio-controller/go.sum
manifests/base/crd/overlays/local-dev/kustomization.yaml
tests-e2e/core/environment_test.go
tests-e2e/core/managed_environment_test.go
tests-e2e/fixture/environment/fixture.go
tests-e2e/go.mod
tests-e2e/go.sum

- Update errors in status.conditions field of Environment
- Unit tests and e2e tests
https://issues.redhat.com/browse/GITOPSRVCE-498

Update error in status.conditions field of Environment

---

appstudio-controller/config/rbac/role.yaml
appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller.go

* Update sandbox provisioner kubebuilder directives
[STONEINTG-261](https://issues.redhat.com//browse/STONEINTG-261)

fix(STONEINTG-261): refer to resources in plural

---

scripts/openshiftci-presubmit-e2e-tests.sh

This PR is to update script used for running E2E by OpenShift CI.
https://issues.redhat.com/browse/GITOPSRVCE-220

update E2E script.

---

create-dev-env.sh
manifests/scripts/metrics-dashboard/postgresql/grafana-postgresql-dashboard-cm.yaml
manifests/scripts/metrics-dashboard/postgresql/grafana-postgresql-dashboard.yaml
manifests/scripts/metrics-dashboard/postgresql/postgresql-data-source.yaml
manifests/scripts/metrics-dashboard/run.sh
psql.sh

- See Jira for more details including test steps.
- Sets up the dev env and in particular, the kube-auto target
- Probably in production, it is suggested to use a DB user that has more restrictions, like it shouldn't be allowed to delete tables.
*See JIRA for review instructions*
See https://issues.redhat.com/browse/GITOPSRVCE-491

Add PostgreSQL Data Source and Grafana dashboard (#491)

---

appstudio-controller/controllers/appstudio.redhat.com/application_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
appstudio-controller/controllers/appstudio.redhat.com/devsandbox_deployment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshot_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/go.mod
appstudio-controller/main.go
backend-shared/util/log.go
tests-e2e/go.mod

This PR is to update logs to ADR6 format.
https://issues.redhat.com/browse/GITOPSRVCE-549

log refinement to ADR6.

---

manifests/base/gitops-service-argocd/base/argo-cd.yaml
manifests/base/gitops-service-argocd/overlays/appstudio-staging-and-prod/argo-cd-patch.yaml
manifests/base/gitops-service-argocd/overlays/appstudio-staging-and-prod/kustomization.yaml
manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/kustomization.yaml

- As the title says, increase the maximum amount of memory available to Argo CD application controller container, and increase the CPU limit.
- Also remove the old init container, which was only temporarily needed.

Increase available memory for Argo CD application controller container, on dev/staging

---

backend/controllers/managed-gitops/gitopsdeployment_controller.go
backend/controllers/managed-gitops/gitopsdeploymentmanagedenvironment_controller.go
backend/controllers/managed-gitops/gitopsdeploymentrepositorycredential_controller.go
backend/controllers/managed-gitops/gitopsdeploymentsyncrun_controller.go
backend/controllers/managed-gitops/secret_controller.go
backend/eventloop/application_event_loop/application_event_loop.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/controller_event_loop.go
backend/eventloop/db_metrics.go
backend/eventloop/db_reconciler.go
backend/eventloop/preprocess_event_loop/preprocess_event_loop.go
backend/eventloop/repocred_reconciler.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/workspace_event_loop.go
backend/eventloop/workspace_resource_event_loop.go
backend/main.go
tests-e2e/go.mod

This PR is to update logs to ADR6 format.
https://issues.redhat.com/browse/GITOPSRVCE-551

log refinement to ADR6. #437

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go

- Update the binding condition status if the previous set repo condition status is updated
- Add unit test
https://issues.redhat.com/browse/GITOPSRVCE-556

Update the binding condition if the repo condition status is updated

---

manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml

- Does what it says on the tin :grin:

Update appstudio-controller container memory limit

---

appstudio-controller/config/rbac/role.yaml
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller_test.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller_test.go
appstudio-controller/controllers/appstudio.redhat.com/predicates_dt.go
appstudio-controller/controllers/appstudio.redhat.com/predicates_dt_test.go
appstudio-controller/main.go
tests-e2e/core/deploymenttargetclaim_binder_test.go
tests-e2e/core/environment_test.go
tests-e2e/core/sandboxprovisioner_test.go

Add DeploymentTarget controller
React to DeploymentTarget CR  with delete action using predicate
Reclaim DeploymentTarget and delete related SpaceRequest CR
Add unit tests for the new functionality
[STONEINTG-336](https://issues.redhat.com/browse/STONEINTG-336)

DeploymentTarget CR reconciler

---

scripts/openshiftci-presubmit-e2e-tests.sh

Add loop to the port-forward connection to automatically reconnect on fail. 
https://issues.redhat.com/browse/GITOPSRVCE-456

Add port-forward loop

---

.tekton/push-release-summit-2023.yaml

- Add a new PipelineRun for release branch, to see if this can be used to enable building from another branch

Add new tekton PipelineRun to build from release branch

---

appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
backend-shared/util/proxyclient.go

- Add additional checks to prevent calls to `k8sClient.Status().Update` in cases where the `.status.bindingConditions` field was not actually modified.
- Remove duplication from the condition update logic of the SnapshotEnvironmentBinding/Environment CRs, since both CRs are doing the exact same thing (updating []metav1.Condition)
- (It would not surprise me if there existed a utility function in k8s api packages that did this, but one thing at a time)
- Add new unit tests for above
- Added short log statements to indicate when the .status.bindingConditions field is being updated, to help us detect this during dev
- Fix status-update bug in our proxy client (proxy client is used in various unit tests)

Prevent excessive status updates on  .status conditions of SnapshotEnvironmentBinding/Environment resources

---

backend-shared/db/operations.go
backend-shared/db/queries.go
backend-shared/db/unreliable_db_client.go
backend-shared/util/operations/types.go
backend-shared/util/operations/types_test.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/db_reconciler.go
backend/eventloop/db_reconciler_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential.go
cluster-agent/controllers/argoproj.io/application_controller_test.go
cluster-agent/controllers/argoproj.io/namespace_reconciler.go
cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
tests-e2e/core/operation_namespace_test.go

This PR is to add a clean up job to remove orphaned entries from Operation table and CR from cluster.
https://issues.redhat.com/browse/GITOPSRVCE-423

Periodically clean up of orphaned CRs.

---

appstudio-controller/config/webhook/manifests.yaml
appstudio-controller/go.mod
appstudio-controller/go.sum
appstudio-controller/main.go
manifests/base/crd/overlays/local-dev/kustomization.yaml
tests-e2e/appstudio/webhook_test.go
tests-e2e/go.mod
tests-e2e/go.sum

This PR is to update webhook configs in managed-gitops that is implemented in application-api repo.
https://issues.redhat.com/browse/GITOPSRVCE-573

Environment CR webhook validation.

---

backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_deployments_test.go
tests-e2e/argocd/argocd_application_test.go
tests-e2e/core/gitopsdeployment_status_test.go
tests-e2e/fixture/application/fixture.go

https://issues.redhat.com/browse/GITOPSRVCE-575

Set retry limit for Argo CD app.

---

backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential.go

- In backend , there are some places where error was placed as first parameter, fixed the error placement

Fix the placement of the error parameter

---

appstudio-controller/config/webhook/manifests.yaml

- Temporarily remove the Webhook manifest, to avoid issue reported on RHTAPBUGS

Temporarily remove environment webhook

---

appstudio-controller/config/rbac/role.yaml
appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
tests-e2e/core/dt_dtc_dtclass_test.go
tests-e2e/core/managed_environment_test.go

- The Environment controller should convert a SpaceRequest secret into a ManagedEvironment secret.
https://issues.redhat.com/browse/GITOPSRVCE-586

Convert SpaceRequest secret into a ManagedEnvironment secret

---

backend-shared/db/clusteraccess.go
backend-shared/db/clustercredentials.go
backend-shared/db/clusteruser.go
backend-shared/db/gitopsenginecluster.go
backend-shared/db/queries.go
backend-shared/db/unreliable_db_client.go
backend/eventloop/db_reconciler.go
backend/eventloop/db_reconciler_test.go
tests-e2e/go.mod
tests-e2e/go.sum

This PR is to add a clean up job for ClusterUser and ClusterCredential tables.
https://issues.redhat.com/browse/GITOPSRVCE-437

Periodically clean up of orphaned table entries.

---

backend-shared/util/util.go
backend/eventloop/db_reconciler.go
cluster-agent/controllers/argoproj.io/namespace_reconciler.go

This PR is to update logging for periodic clean jobs for better analysis and detection.
https://issues.redhat.com/browse/GITOPSRVCE-438

clean up job logging.

---

tests-e2e/core/queryscoped_cluster_secrets_test.go
tests-e2e/fixture/k8s/fixture.go

- New E2E test that verifies that using `?managedEnvironment=(managed environment id)` at the end of a Argo CD cluster Secret URL will cause Argo CD to treat the cluster as a separate cluster.
- Some refactoring of shared functions into fixture (the code for the functions themselves is unchanged)

Add E2E test for Argo CD query-scoped GitOpsDeployments

---

backend-shared/util/log/log.go

See https://issues.redhat.com/browse/GITOPSRVCE-593 for details of the change and for pre-review comments

Restrict LogAPIResourceChangeEvent log contents (#593)

---

backend/eventloop/db_reconciler.go

This PR is to fix a bug in periodically clean up job.
https://issues.redhat.com/browse/GITOPSRVCE-643

Periodically clean up fix.

---

backend/eventloop/db_reconciler.go

This PR is to do some code refactoring in clean up job for better performance.
https://issues.redhat.com/browse/GITOPSRVCE-609

code refactoring for better performance.

---

appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller.go
appstudio-controller/controllers/appstudio.redhat.com/devsandbox_deployment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller.go

- Added LogAPIResourceChangeEvent in DT/DTC/DTClaim code and also in other parts of code where LogAPIResourceChangeEvent is missing
https://issues.redhat.com/browse/GITOPSRVCE-577

Add LogAPIResourceChangeEvent for DT/DTC/DTClaim code

---

manifests/scripts/openshift-argo-deploy/openshift-gitops-subscription.yaml

https://issues.redhat.com/browse/GITOPSRVCE-660

Upgrade  OpenShift Gitops version to 1.9

---

manifests/scripts/metrics-dashboard/postgresql/grafana-postgresql-exporter-dashboard-cm.yaml
manifests/scripts/metrics-dashboard/postgresql/grafana-postgresql-exporter-dashboard.yaml
manifests/scripts/metrics-dashboard/run.sh

See https://issues.redhat.com/browse/GITOPSRVCE-511 for details
To launch from your own development environment, just run:
make setup-e2e-openshift
manifests/scripts/metrics-dashboard/run.sh

Add time series database metrics and grafana dashboard (#511)

---

backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go

- When the connection to a cluster fails due to the cluster certificate being signed by an unknown authority, explicitly report this in the error status condition

Explicitly report cert authority invalid error

---

backend-shared/db/apicrtodatabasemapping.go
backend-shared/db/clusteraccess.go
backend-shared/db/clusteruser.go
backend-shared/db/deploymenttoapplicationmapping.go
backend-shared/db/gitopsenginecluster.go
backend-shared/db/operations.go
db-schema.sql
utilities/db-migration/migrations/000001_init_db.up.sql
utilities/db-migration/migrations/000017_v17.down.sql
utilities/db-migration/migrations/000017_v17.up.sql

See https://issues.redhat.com/browse/GITOPSRVCE-561
See https://issues.redhat.com/browse/GITOPSRVCE-561

Ensure we have database indexes the DB queries we are using (#561)

---

backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/workspace_event_loop.go
backend/eventloop/workspace_event_loop_test.go

- Improve test coverage of the `processWorkspaceEventLoopMessage` function
- Minor refactoring to make it easier to write elegant unit tests

Add additional unit tests for the workspace event loop

---

backend/eventloop/db_reconciler.go
backend/eventloop/db_reconciler_test.go

https://issues.redhat.com/browse/GITOPSRVCE-658

Add delete logic for ApplicationState from cleanOrphanedEntriesfromTable_Application

---

appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
tests-e2e/core/environment_test.go
tests-e2e/fixture/environment/fixture.go

- Added a new status condition which will be less subject to misinterpretation

Improve the Environment error reporting APIs

---

docs/deployment-target-claim-class-steps.md

- I previously wrote a step by step explanation/interpretation of the ADR 8 document, so that I could fully understand the ADR 8 spec doc, and so I could review code written by both our team and by the RHTAP integration team.
- At the time, the doc I wrote lived on hackmd.io. A better home for it is in the managed-gitops repo.

Contribute my DeploymentTarget/Claim/Class 'step by step' doc to the repo

---

backend/eventloop/application_event_loop/application_event_loop_test.go

- Some changes were merged (by me) after we enabled the ginkgolinter CI check, so those changes were still under the old regime and caused CI check fails for other PRs.
- This fixes the issues flagged by ginkgolinter.

Fix ginkgolinter ci check failures

---

.tekton/pull-request.yaml
.tekton/push.yaml

- Switch to the resolver at the request of the pipelines team

Update .tekton YAML based on release-service repo

---

.codecov.yml

- Add a few more files that are only used for testing, to the codecov.yml ignore list

Add additional test-only files to .codecov.yml ignore list

---

backend-shared/util/argocd/util.go
backend-shared/util/argocd/util_test.go
backend/config/rbac/role.yaml
backend/eventloop/cluster_reconciler.go
backend/eventloop/cluster_reconciler_test.go
backend/main.go

- Add a reconciliation loop that periodically inspects if a resource is orphaned in a cluster
- If it is orphaned, the resource will be deleted
- Update clusterole to give additional permissions(get,list,delete) for backend
- Add unit tests
https://issues.redhat.com/browse/GITOPSRVCE-653

Clean up K8s resources orphaned by Argo CD

---

Makefile
backend-shared/util/argocd/util.go
backend-shared/util/argocd/util_test.go
backend/eventloop/cluster_reconciler.go
backend/eventloop/cluster_reconciler_test.go

- Resources that were not orphaned are being deleted, due to a bug in parsing the application value
- Updates to unit tests to fix test issues that should have identified the above problem.

Prevent deletion of non-orphaned Argo CD deployed resources 

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go

- Added a new status condition which will be less subject to misinterpretation.

Improve SnapshotEnvironmentBinding error reporting APIs

---

cluster-agent/controllers/util.go
cluster-agent/controllers/util_test.go

These changes should test the 'if !success {' part excluding the conditions that handle more general error situations.  Run the tests and observe the log statements
See https://issues.redhat.com/browse/GITOPSRVCE-700

Improve test coverage of DeleteArgoCDApplication in cluster-agent (#700)

---

tests-e2e/appstudio/environment_test.go

[tests-e2e/core/environment_test.go → tests-e2e/appstudio/environment_test.go](https://github.com/redhat-appstudio/managed-gitops/compare/main...jgwest:managed-gitops:move-environment-e2e-test-may-2023?expand=1#diff-169b9874a213bf183b0dac8ad1e77ff10c6a8957ccf87ec80c83c4992eef5e02)

Move Appstudio Environment E2E tests from core folder to appstudio folder

---

appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller_test.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
appstudio-controller/go.mod
appstudio-controller/go.sum
manifests/base/crd/overlays/local-dev/kustomization.yaml
tests-e2e/appstudio/snapshotenvironmentbinding_test.go
tests-e2e/go.mod
tests-e2e/go.sum
utilities/load-test/go.mod
utilities/load-test/go.sum

- Pick up the latest changes from [GITOPSRVCE-646](https://issues.redhat.com//browse/GITOPSRVCE-646) into appstudio-controller

Bring SnapshotEnvironmentBinding webhook changes from application-api into appstudio-controller

---

backend-shared/db/apicrtodatabasemapping_test.go
backend-shared/db/application_test.go
backend-shared/db/clusteraccess_test.go
backend-shared/db/clustercredentials_test.go
backend-shared/db/clusteruser_test.go
backend-shared/db/gitopsenginecluster_test.go
backend-shared/db/kubernetesresourcetodbresourcemapping_test.go
backend-shared/db/managedenvironment_test.go
backend-shared/db/operations_test.go
backend-shared/db/repo_cred_test.go
backend-shared/db/syncoperation_test.go

This PR is to add unit test cases for batch functions in backend-shared component.
https://issues.redhat.com/browse/GITOPSRVCE-691

chore: improve test coverage for backend-shared.

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentrepositorycredential_types_test.go

This PR is to add unit test cases for gitopsdeploymentrepositorycredential_types.go file of backend-shared.
https://issues.redhat.com/browse/GITOPSRVCE-690

chore: improve test coverage.

---

cluster-agent/utils/argocd_login_command.go
cluster-agent/utils/argocd_login_command_test.go
cluster-agent/utils/argocd_login_credentials.go

- Add unit test for generateDefaultClientForServerAddress function
https://issues.redhat.com/browse/GITOPSRVCE-698

Add unit test for generateDefaultClientForServerAddress function

---

manifests/base/postgresql-staging/postgresql-staging.yaml
manifests/overlays/appstudio-staging-cluster/appstudio-controller-deployment-patch.yaml
manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
manifests/overlays/appstudio-staging-cluster/cluster-agent-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/cluster-agent-deployment-patch.yaml

- Fix initial set of warnings from kubelinter, against infra-deployments repo

Fix initial set of kubelinter warnings

---

appstudio-controller/go.mod
appstudio-controller/go.sum
manifests/base/crd/overlays/local-dev/kustomization.yaml
tests-e2e/appstudio/webhook_test.go
tests-e2e/fixture/k8s/fixture.go
tests-e2e/go.mod
tests-e2e/go.sum
utilities/load-test/go.mod
utilities/load-test/go.sum

- E2E tests for https://issues.redhat.com/browse/GITOPSRVCE-646

E2E tests for SEB webhook

---

backend-shared/db/app_project_managed_env.go
backend-shared/db/app_project_managed_env_test.go
backend-shared/db/app_project_repository_test.go
backend-shared/db/application_test.go
backend-shared/db/clusteraccess.go
backend-shared/db/clusteraccess_test.go
backend-shared/db/operations.go
backend-shared/db/operations_test.go
backend-shared/db/queries.go
backend-shared/db/test_utils.go
backend-shared/db/unreliable_db_client.go
cluster-agent/controllers/util_test.go

- Add unit tests for the missing list functions
https://issues.redhat.com/browse/GITOPSRVCE-692

Add unit tests for the missing List DB queries

---

.gitleaks.toml
docs/api.md

- Add DeploymentTarget/DeploymentTargetClaim/DeploymentTargetClass API example to API doc

Add DeploymentTarget/DeploymentTargetClaim/DeploymentTargetClass API example to API doc

---

backend/eventloop/workspace_event_loop_test.go

- Improve test coverage of workspace event loop
https://issues.redhat.com/browse/GITOPSRVCE-697

Improve test coverage of workspace event loop

---

OWNERS

- Update OWNERS with currently active reviewers

Update OWNERS with currently active reviewers

---

appstudio-controller/config/webhook/manifests.yaml
tests-e2e/appstudio/environment_test.go
tests-e2e/appstudio/webhook_test.go

E2E test for Environment API
https://issues.redhat.com/browse/GITOPSRVCE-727

Add e2e tests for invalid apiURL in Environment API

---

appstudio-controller/config/tmp-default-webhook-with-env/kustomization.yaml
appstudio-controller/config/tmp-default-webhook-with-env/manager_auth_proxy_patch.yaml
appstudio-controller/config/tmp-default-webhook-with-env/manager_config_patch.yaml
appstudio-controller/config/tmp-default-webhook-with-env/manager_webhook_patch.yaml
appstudio-controller/config/tmp-default-webhook-with-env/webhookcainjection_patch.yaml
appstudio-controller/config/tmp-webhook-with-env/kustomization.yaml
appstudio-controller/config/tmp-webhook-with-env/kustomizeconfig.yaml
appstudio-controller/config/tmp-webhook-with-env/manifests.yaml
appstudio-controller/config/tmp-webhook-with-env/service.yaml
manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/appstudio-controller-deployment-patch.yaml
manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/backend-deployment-patch.yaml
manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/cluster-agent-deployment-patch.yaml
manifests/overlays/tmp-stonesoup-member-cluster-env-webhook/kustomization.yaml

- Create temporary overlays which have the Environment webhook enabled, so we can debug the issue by enabling that webhook on RHTAP staging (only)

GITOPSRVCE-771: add temp overlays for debugging env webhook

---

backend-shared/db/postgres-integration.go

- For, skip certification validation when connecting to postgresql server.

GITOPSRVCE-731: add InsecureSkipVerify to postgresql connection settings

---

appstudio-controller/config/default-no-webhook/manager_auth_proxy_patch.yaml
appstudio-controller/config/default/manager_auth_proxy_patch.yaml
backend/config/default/manager_auth_proxy_patch.yaml
cluster-agent/config/default/manager_auth_proxy_patch.yaml
manifests/overlays/appstudio-staging-cluster/appstudio-controller-deployment-patch.yaml
manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
manifests/overlays/appstudio-staging-cluster/cluster-agent-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/cluster-agent-deployment-patch.yaml

- In response to rapid reset CVE, move up to latest kube-rbac-proxy, and add -http2-disable=true

Move up to latest kube-rbac-proxy, and add -http2-disable=true

---

backend-shared/db/apicrtodatabasemapping_test.go
backend-shared/db/app_project_repository_test.go
backend-shared/db/application_test.go
backend-shared/db/syncoperation.go
backend-shared/db/syncoperation_test.go

- Add additional unit tests for DB Queries
https://issues.redhat.com/browse/GITOPSRVCE-693

Add additional DB unit tests

---

cluster-agent/utils/argocd_create.go

- Retry if there is a conflict while updating the service account
https://issues.redhat.com/browse/GITOPSRVCE-782

fix intermittent E2E test failure in 'argocd_instance_test.go'

---

utilities/gitopsctl/implementations/parse-json-logs/parse-json-logs.go

- Simple fix to parsing of timestamp within non-Splunk logs

gitopsctl: fix timestamp parsing of non-splunk controller logs

---

manifests/base/monitoring/grafana-dashboards-new/gitops-dashboard.json
manifests/base/monitoring/grafana-dashboards/managed-gitops/gitops-dashboard.json
manifests/base/monitoring/grafana-dashboards/stonesoup/gitops-dashboard.json

- There was some glitch in GitOps Service Grafana Dashboard for Operation DB Rows, Fixed it

Fix grafana dashboard for operation DB rows

---

backend/eventloop/cluster_reconciler.go
backend/eventloop/db_reconciler.go
cluster-agent/controllers/argoproj.io/namespace_reconciler.go
docs/self-healing-mechanism.md

- We have a fair bit of code in GitOps Service whose responsibility is to ensure that cluster state is always synchronized with user intent.
- This task is for documenting how this logic works.
- Plus some code comment additions

GITOPSRVCE-793: document GitOps Service's self-healing mechanism

---

tests-e2e/appstudio/snapshotenvironmentbinding_test.go
tests-e2e/fixture/binding/fixture.go

-E2E tests for binding conditions in snapshotenvironmentbinding_test.go file
https://issues.redhat.com/browse/GITOPSRVCE-730

Add e2e tests for BindingConditions

---

appstudio-controller/controllers/appstudio.redhat.com/deploymenttarget_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetclaim_controller.go
appstudio-controller/go.mod
appstudio-controller/go.sum
manifests/base/crd/overlays/local-dev/kustomization.yaml
tests-e2e/appstudio/deploymenttargetclaim_binder_test.go
tests-e2e/appstudio/dt_dtc_dtclass_test.go
tests-e2e/appstudio/environment_test.go
tests-e2e/fixture/deploymenttarget/fixture.go
tests-e2e/fixture/deploymenttargetclaim/fixture.go
tests-e2e/go.mod
tests-e2e/go.sum
utilities/load-test/go.mod
utilities/load-test/go.sum

This PR is to add logic in DeploymentTarget and DeploymentTargetClaim controllers to update new `Conditions` filed in `status`.
https://issues.redhat.com/browse/GITOPSRVCE-627

Error reporting in DeploymentTarget/DeploymentTargetClaim.

---

docs/environment-api/introduction.md

- An initial, introductory overview of the Environment API

Add Environment API introduction doc

---

manifests/overlays/appstudio-staging-cluster/appstudio-controller-deployment-patch.yaml
manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
manifests/overlays/appstudio-staging-cluster/cluster-agent-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/cluster-agent-deployment-patch.yaml

- Deprecate Konflux deployment via infra-deployments repo

Deprecate Konflux deployment

---

resources/test-data/sample-gitops-repository/components/componentA/base/kustomization.yaml
resources/test-data/sample-gitops-repository/components/componentB/base/kustomization.yaml

- Remove Route from set of required resources in E2E test data

Remove Route from set of required resources in E2E test data

---

docs/building.md
docs/components.md
docs/designs/conversion-webhook-support-without-controller-runtime-dependency.md
docs/designs/gitopsdeploymentmanagedenvironment-api-cluster-add-behaviour.md
docs/designs/initial-api-design.md
docs/designs/mapping-gitops-repo-git-commit-to-and-from-snapshot.md
docs/designs/private-repository-support-for-a-fixed-set-of-gh-orgs.md
docs/designs/rethinking-argo-cd-architecture-in-gitops-service.md
docs/designs/sandboxing-user-namespaces-via-argo-cd-appprojects.md
docs/profiling.md
docs/sandboxing-via-appprojects.md

- Additional migration of previously written Managed GitOps Service architecture and design docs to GitHub

Additional migration of Managed GitOps Service architecture and design docs
