backend-shared/config/db/application.go
backend-shared/config/db/applicationstates.go
backend-shared/config/db/clusteraccess.go
backend-shared/config/db/clustercredentials.go
backend-shared/config/db/clusteruser.go
backend-shared/config/db/deploymenttoapplicationmapping.go
backend-shared/config/db/gitopsenginecluster.go
backend-shared/config/db/gitopsengineinstance.go
backend-shared/config/db/managedenvironment.go
backend-shared/config/db/operations.go
backend-shared/config/db/queries.go
backend-shared/config/db/types_test.go
backend-shared/config/db/utils.go

Add context parameter to all database queries, allowing us to support timeout and cancel functions on goroutines that are invoking the database.

Add context param to all database queries

---

backend-shared/config/db/clusteruser.go
backend-shared/config/db/gitopsenginecluster.go
backend-shared/config/db/kubernetesresourcetodbresourcemapping.go
backend-shared/config/db/managedenvironment.go
backend-shared/config/db/operations.go
backend-shared/config/db/queries.go
backend-shared/util/utils.go
db-schema.sql

This PR:
- Adds `UncheckedGetOrCreateManagedEnvironmentByNamespaceUID` function, for use by cluster-agent and backend
- Adds additional unchecked DatabaseQueries interface methods to support that
- Misc comments and cleanup

Add UncheckedGetOrCreateManagedEnvironmentByNamespaceUID function for use by cluster-agent and backend

---

backend-shared/config/db/apicrtodatabasemapping.go
backend-shared/config/db/deploymenttoapplicationmapping.go
backend-shared/config/db/gitopsengineinstance.go
backend-shared/config/db/managedenvironment.go
backend-shared/config/db/queries.go
backend-shared/config/db/syncoperation.go
backend-shared/config/db/types.go
backend-shared/config/db/types_test.go
backend-shared/util/utils.go
backend/Makefile
backend/eventloop/eventloopinternal.go
backend/util/util.go
db-schema.sql

This PR:
- Adds applications scoped DB resources, which are resources that are are not shared between gitopsdeployments
- Adds application-scoped disposable resources
- Removes cascade delete from the schema (and fixes tests to match)

Add app-scoped DB query, app-scoped disposable resources, and remove cascade delete from schema

---

.github/workflows/static.yml
create-dev-env.sh
psql.sh

In a nutshell:
* Make sure requires binaries are present to the local system (see `exit_if_binary_not_installed` function)
* Use `psql` as part of the postgres container (thus `psql.sh` is not needed anymore)
* refactor the 30-sec loop using the `wait-until` function so it aborts if there's failure
* create some variables for strings used in multiple places (e.g. container names)
* remove `-t` from the docker commands, otherwise CI fails.
* introduce testing after each command to make sure they work

Refactor devenv script

---

Makefile
Procfile
README.md
cluster-agent/main.go

Similar to how Argo CD uses a goreman + a Procfile to invoke the various Argo CD services simultaneously in a local development environment, we can do the same here.
Plus I've added a `Makefile` to contain targets that operate on multiple components simultaneously, such as this new goreman invocation via `make start`.

Add support for running backend+cluster-agent as a single unit, using goreman

---

cluster-agent/controllers/managed-gitops/suite_test.go

While I was testing #51 my my `golangci-linter` errors out for this:
```
[drpaneas@pgeorgia-mac cluster-agent (main ✗)]$ golangci-lint run ./...
controllers/managed-gitops/suite_test.go:40:5: `cfg` is unused (deadcode)
var cfg *rest.Config
^
```
This is because the PR is adding linting for the `cluster-agent` repo, which was previously missing. See https://github.com/redhat-appstudio/managed-gitops/pull/51/files#diff-33f2778a5bb1ccf0ce7a73eeeeb02daf6023c2bdb47ff841fcf782fc3e469404R55
This issue was not detected by the CI, because changes in the CI take effect _after_ they are merged. So, this PR is required to me merged prior to #51 . Otherwise the Ci will be broken afterwards.

Fix golangci for cluster-agent

---

Makefile
README.md

When I tried `make start` it failed because the makefile expects `goreman` to be located at `~/go/bin`. I am not using `~/go/bin` for the go binaries but I do use `GOBIN` env variable to handle them. GOBIN is basically `GOPATH/bin` which is the place here the go binaries go after running `go install`. Would that work for you?
Also modified the readme at there is no more `make install` target and did some syntax cleanup.

Use GOBIN instead of ~/go/bin/

---

.github/workflows/docker-image.yml

We used to have a bunch of broken Dockerfiles.
This PR makes sure the Dockerfile we have always builds.
See an example of a run, from my fork: https://github.com/drpaneas/managed-gitops/runs/5005481612?check_suite_focus=true
PS: this is the default template for Dockerfile building recommended by GitHub Actions.

Test dockerfile

---

backend-shared/config/db/ephemeralPostgres.go
backend-shared/config/db/ephemeralPostgres_test.go
backend-shared/config/db/postgres-integration.go
backend-shared/config/db/queries.go

Hi, :hugs:!
This is in regards with issue GITOPS-1634, this PR mainly involves two main methods (NewEphemeralCreateTestFramework, and, NewEphemeralCleanTestFramework) which are responsible for creating and cleaning a ephemeral, disposable Postgresql container which is being merely used for testing purpose.
The tests written against above method might look like this:
```
func TestEphemeralCode(t *testing.T) {
ctx := context.Background()
// Create ephemeral DB
ephemeralDB, err := NewEphemeralCreateTestFramework()
assert.NoError(t, err)
dbq := ephemeralDB.db
defer dbq.CloseDatabase()
// test code as normal, for example:
var applicationStates []ApplicationState
err = dbq.UnsafeListAllApplicationStates(ctx, &applicationStates)
assert.NoError(t, err)
errClean := …
```

Add test framework code for testing database tests (Solves: GITOPS-1634)

---

backend-shared/config/db/syncoperation.go
backend-shared/config/db/types.go
backend/eventloop/application_event_runner.go
backend/eventloop/preprocess_event_loop.go
backend/eventloop/sharedresourceloop.go
db-schema.sql
docs/manifests.md
docs/run.md
manifests/database-init/job.yaml
manifests/staging-package/generate-staging-package.sh

This PR:
- Adds `desired_state` to SyncOperation
- Add logic to handle deletion of a GitOpsDeploymentSyncRun CR; deletion of this API CR should cancel any sync operations that are running in Argo CD (but this sync cancellation logic will be in a separate PR).
This is a small chunk of a larger piece of work that I am still working on as part of manual sync. Because manual sync was depriotized in favour of automated sync, for this sprint, I am pushing this small piece as a PR so it doesn't get lost/out-of-sync with the rest of the codebase.

Update database schema for manual sync

---

.dockerignore
cluster-agent/go.mod

Fixes a bug, when running `make docker-build docker-push IMG=quay.io/pgeorgia/gitops-service:lates` from a Mac system:
```
...
...
#15 151.5 go: downloading go.starlark.net v0.0.0-20200306205701-8dd3e2ee1dd5
#15 154.1 go vet ./...
#15 278.4 go build -o bin/manager main.go
#15 294.8 make[1]: Leaving directory '/workspace/cluster-agent'
#15 294.8 cd /workspace/appstudio-controller && make build
#15 294.8 make[1]: Entering directory '/workspace/appstudio-controller'
#15 294.9 /workspace/appstudio-controller/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
#15 294.9 bash: line 1: /workspace/appstudio-controller/bin/controller-gen: cannot execute binary file: Exec format error
#15 294.9 make[1]: Leaving directory '/workspace/appstudio-controller'
#15 294.9 make[1]: …
```

Fix appstudio-controller docker-build for Mac

---

cluster-agent/go.mod
manifests/postgresql-staging/postgresql-staging.yaml

This PR is in association with [https://issues.redhat.com/browse/GITOPSRVCE-98](https://issues.redhat.com/browse/GITOPSRVCE-98). It aims to migrate the PostgreSQL database to use a Red Hat supported PostgreSQL image in place of the existing Bitnami image.

migration of postgres from a bitnami to a rhel image

---

backend/eventloop/application_event_loop/application_event_loop.go
backend/eventloop/application_event_loop/application_event_loop_test.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/application_event_loop/application_eventloop_suite_test.go
backend/eventloop/controller_event_loop.go
backend/eventloop/controller_event_loop_test.go
backend/eventloop/event_loop_suite_test.go
backend/eventloop/eventlooptypes/types_test_util.go
backend/eventloop/preprocess_event_loop.go
backend/eventloop/preprocess_event_loop_test.go
backend/eventloop/workspace_event_loop.go
backend/eventloop/workspace_event_loop_test.go

This PR:
- Refactors the event loop tests, adding mocking so that each event loop layer can be testing independently from the others
- Switches existing event loop test to Ginkgo test API
- Adds very simple tests that use those mocks, will create stories to add less simple tests.

Refactor event loop tests and switch to Ginkgo

---

appstudio-controller/go.sum
backend-shared/config/db/util/utils.go
backend/condition/conditions_suite_test.go
backend/condition/conditions_test.go
backend/controllers/managed-gitops/suite_test.go
backend/eventloop/application_event_loop/application_event_loop_test.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/application_event_loop/application_eventloop_suite_test.go
backend/eventloop/controller_event_loop_test.go
backend/eventloop/event_loop_suite_test.go
backend/eventloop/preprocess_event_loop_test.go
backend/eventloop/shared_resource_loop/shared_resource_loop_suite_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
backend/eventloop/workspace_event_loop_test.go
backend/go.mod
backend/go.sum
backend/main.go

This PR is to add Unit test cases for sharedresourceloop.
1. Added unit test cases for following functions
- GetOrCreateClusterUserByNamespaceUID
- GetOrCreateSharedResources
- . GetGitopsEngineInstanceById
2. Updated signature of functions to return flags to identify whether resources were newly created or fetched from existing entry.
3. Used a cleanup function delete resources created by tests.
1. Upgraded Ginkgo to V2.0 in `backend` (Can be done for other components in separate PR.) for using `DeferCleanup` to clean up resources after each test.
2. Changed Ginkgo import statements in `backend`.
3. Replaced `RunSpecsWithDefaultAndCustomReporters` with `RunSpecs` in `backend/controllers/managed-gitops/suite_test.go`, as it's been deprecated in Ginkgo V2. …

Add unit tests for sharedresourceloop

---

.tekton/push.yaml

This PR moves the CI previously defined in the [infra-deployments](https://github.com/CathalOConnorRH/infra-deployments/blob/637e85d68679d81cff2c4f03a9354145a1f7936d/components/gitops/.tekton/trigger-template.yaml) repository to this repository

add tekton ci from infra-deployments

---

.tekton/pull-request.yaml
.tekton/push.yaml

As PVC is created for the whole namespace and the pipelineRun is using subPath, the PVC was being full very soon, and to overcome this, as a workaround we used volumeClaimTemplate, which creates PVC for each pipelineRun.
Now, there is a [PVC-cleaner](https://github.com/redhat-appstudio/pvc-cleaner) which will delete the subPath when a pipelineRun is deleted.
This PR is to switch back to subPaths from volumeClaimTemplate.
https://issues.redhat.com/browse/PLNSRVCE-174

 update gitops service to use PVC instead of volumeClaimTemplate

---

cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
cluster-agent/controllers/managed-gitops/operation_controller.go
cluster-agent/main.go

- Very simple PR, just renaming cluster-agent's `eventloop.go` to `operation_event_loop.go`.
- Likewise updating the name of the struct, from `ControllerEventLoop` to `OperationEventLoop`
- The name change is to better clarify the role of this file: receiving events related to `Operation` resource.
- More code comments

Rename cluster-agent's eventloop.go to operation_event_loop.go

---

appstudio-controller/controllers/appstudio.redhat.com/application_controller.go

- Fix improper use of log API: log.Info doesn't support Sprintf-style arguments.

Fix 'odd number of arguments passed as key-value pairs for logging' in appstudio-controller

---

appstudio-controller/controllers/appstudio.redhat.com/application_controller.go

- This fixes a bug seen by [Scott on Red Hat Slack](https://coreos.slack.com/archives/C02C3SE8QS2/p1651755902793099?thread_ts=1651697197.950829&cid=C02C3SE8QS2), where Argo CD did not like a path value of '/' which we were setting in the source field of Argo CD `Application` resource.
- Argo CD  treats '/' as an absolute path, which it does not like :stuck_out_tongue:.
- So if the user specifies `/` in the AppStudio `Application` gitopsrepo context field, we will rewrite it to `.`, so that Argo CD is happy.

If AppStudio Application uses '/' as Git Repo Path, rewrite it to ., to make Argo CD happy

---

backend-shared/config/db/application_test.go
backend-shared/config/db/gitopsenginecluster_test.go
backend-shared/config/db/gitopsengineinstance_test.go
backend-shared/config/db/kubernetesresourcetodbresourcemapping_test.go
backend-shared/config/db/managedenvironment_test.go
backend-shared/config/db/operations_test.go

Migrates the following test files into ginkgo : 
- application_test.go
- gitopsenginecluster_test.go
- gitopsengineinstance_test.go
- kubernetestodbresourcemapping_test.go
- managedenvironment_test.go
- operation_test.go
(https://issues.redhat.com/browse/GITOPSRVCE-121)

Add ginkgo migration for existing test files

---

.ci/openshift-ci/Dockerfile

- This is in regard to the story for enabling openshift-ci on managed-gitops, for the same when we do `make devenv-k8s` in our Makefile we are extensively using kubectl. But, kubectl is not installed in openshift-ci and reports an error as below. 
Error:
```
kubectl create namespace gitops 2> /dev/null || true
kubectl -n gitops apply -f  /go/src/github.com/redhat-appstudio/managed-gitops/backend/config/crd/bases/managed-gitops.redhat.com_gitopsdeployments.yaml
make: kubectl: Command not found
make: *** [deploy-backend-crd] Error 127
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test …
```

Add Dockerfile in .ci/ for to run kubectl in openshift-ci

---

.ci/openshift-ci/Dockerfile

- This is in regard to the story for enabling openshift-ci on managed-gitops. Adding postgres-server for the Dockerfile which is required in order to access psql binary required by the ci!

Adds postgres-server packager to dockerfile, req by openshift-ci

---

backend-shared/config/db/ephemeralPostgres_test.go
backend-shared/config/db/utils.go

On testing the `TestEphemeralCode` function on Openshift-CI
```
--- FAIL: TestEphemeralCode (0.00s)
ephemeralPostgres_test.go:18: 
Error Trace:	ephemeralPostgres_test.go:18
Error:      	Received unexpected error:
unable to create docker network: exec: "docker": executable file not found in $PATH. Do a 'docker system prune', for now
Test:       	TestEphemeralCode
```
This is trying to execute a docker command within the openshift-ci spinned cluster which ideally doesn't have a docker binary installed. Plus, spinning up a container within the container is not a good practice and should be avoided. If folks have more opinions/suggestions around it, please let me know.
The fix to the above failure is to simply skip this test in the Openshift-ci, this is done via checking the environment in …

Add functionality to skip ephemeralPostgres_test in openshift-ci

---

cluster-agent/utils/argocd_login_command_test.go
cluster-agent/utils/argocd_login_credentials_test.go
cluster-agent/utils/argocd_sync_command_test.go
cluster-agent/utils/argocd_terminate_app_command_test.go
cluster-agent/utils/utils_suite_test.go

- This PR is about converting ArgoCD Sync tests to ginkgo in cluster-agent
- Test files which are converted are :
cluster-agent/utils/argocd_login_credentials_test.go
cluster-agent/utils/argocd_terminate_app_command_test.go
cluster-agent/utils/argocd_login_command_test.go
cluster-agent/utils/argocd_sync_command_test.go
https://issues.redhat.com/browse/GITOPSRVCE-123)

Convert ArgoCD Sync tests to ginkgo #123

---

backend-shared/config/db/types_test.go
backend-shared/config/db/util/application_info_cache_test.go
backend-shared/config/db/util/util_suite_test.go

Adds ginkgo tests for : 
- db/types_test.go
- db/util/application_info_cache_test.go
[GITOPSRVCE-124](https://issues.redhat.com/browse/GITOPSRVCE-124)

Add ginkgo test migration for non-group files 

---

backend-shared/config/db/apicrtodatabasemapping.go
backend-shared/config/db/apicrtodatabasemapping_test.go
backend-shared/config/db/db_field_constants.go
backend-shared/config/db/deploymenttoapplicationmapping.go
backend-shared/config/db/deploymenttoapplicationmapping_test.go
backend-shared/config/db/queries.go
backend-shared/config/db/types.go
backend-shared/config/db/util/utils.go
backend/controllers/managed-gitops/gitopsdeployment_controller.go
backend/controllers/managed-gitops/gitopsdeploymentsyncrun_controller.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/eventlooptypes/types_test_util.go
backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
db-schema.sql

- I previously used the term "workspace" as a catch-all term, to refer to the namespace where users were creating our API resources (`GitOpsDeployment` resource, etc).
- However, now that we are moving to KCP, which has the concept of workspaces, this use of 'workspace' is confusing. 
- I have thus updated the code from workspace -> namespace, or workspace -> API namespace as appropriate. 
- This PR only updates names/fields/database rows, there are no functional changes.

Rename database fields and references from workspace to namespace where appropriate

---

.github/workflows/schema-sync.yml
.github/workflows/static.yml

This allows us to hardcode a Go supported [version for the project in a file](https://github.com/actions/setup-go/issues/23#issuecomment-606215099), so then the Go GitHub Action can read that file and run the CI based on _this specific_ Go version. I am wondering if OpenShift CI has something similar (just tagging @samyak-jn to me him aware of this).
The rest of the changelog:
Bumps [actions/setup-go](https://github.com/actions/setup-go) from 3.0.0 to 3.2.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/actions/setup-go/releases">actions/setup-go's releases</a>.</em></p>
<blockquote>
<h2>Support for caching dependency files and compiler's build outputs</h2>
<p>This release introduces support for caching dependency files and compiler's build …

ci: bump actions/setup-go from 3.0.0 to 3.2.0

---

OWNERS

- Add OWNERS file to the managed-gitops repository, required by openshift-ci

Add OWNERS file for ci

---

Makefile
backend/Makefile
backend/routes/router.go
manifests/backend-rbac/managed-gitops-backend-manager-role.yaml

- Fix missing CRD in Makefile, which was preventing backend controller from starting
- Update Repository Credentials backend `Role` resource (for now this is only used when deployed to staging cluster)
- Fix backend time format, now that backend controller moved up to the same controller-runtime version as the other components.
- Verified the new PR passes E2E test

Fix missing CRD in Makefile, update Repository Credentials Role, fix backend time format

---

appstudio-controller/go.mod

-  Today in the slack discussion @drpaneas found out that we have an indirect dependency conflict with db-migration which was breaking development in Goland. This is a quick fix to resolve that issue.
Issue Snap (in appstudio-controller):
```
-> go list -m -json all
go: [github.com/redhat-appstudio/managed-gitops/utilities/db-migration@v0.0.0](http://github.com/redhat-appstudio/managed-gitops/utilities/db-migration@v0.0.0): invalid version: unknown revision utilities/db-migration/v0.0.0
```

Fix module conflict with appstudio-controller caused due to db-migration

---

Makefile
tests-e2e/core/gitops_deployment_status_test.go
tests-e2e/go.mod

Hello folks :hugs:,
- Update make targets to use k8s configurations instead of docker while setting up on openshift (required by openshift-ci)!

Update make targets to use k8s configurations instead of docker while setting up on openshift

---

Makefile

Hello folks :hugs:,
- Add create-db target to use it with openshift-ci setup (required by openshift-ci)!
Why?
```
-setup-e2e-openshift: install-argocd-openshift devenv-k8s reset-db ## Setup steps for E2E tests to run with Openshift CI
+setup-e2e-openshift: install-argocd-openshift devenv-k8s create-db ## Setup steps for E2E tests to run with Openshift CI
setup-e2e-local: install-argocd-openshift devenv-docker reset-db ## Setup steps for E2E tests to run with Local Openshift Cluster
@@ -193,6 +193,9 @@ test-backend-shared: ## Run test for backend-shared only
download-deps: ## Download goreman to ~/go/bin
go install github.com/mattn/goreman@latest
+create-db: ## Create dev enviroment; useful during development
+       $(MAKEFILE_ROOT)/create-dev-env.sh
+
reset-db: ## Erase the current …
```

Add create-db target to use it with openshift-ci setup

---

backend/apis/managed-gitops/v1alpha1/gitopsdeployment_types.go
backend/config/crd/bases/managed-gitops.redhat.com_gitopsdeployments.yaml

- Update the GitOpsDeployment Go struct and CR to accept empty environment field (for now)

Add omitempty back to Environment to maintain compatibility with older resources

---

appstudio-shared/apis/appstudio.redhat.com/v1alpha1/applicationpromotionrun_types.go
appstudio-shared/apis/appstudio.redhat.com/v1alpha1/applicationsnapshot_types.go
appstudio-shared/apis/appstudio.redhat.com/v1alpha1/applicationsnapshotenvironmentbinding_types.go
appstudio-shared/apis/appstudio.redhat.com/v1alpha1/environment_types.go
appstudio-shared/config/crd/bases/appstudio.redhat.com_applicationpromotionruns.yaml
appstudio-shared/config/crd/bases/appstudio.redhat.com_applicationsnapshotenvironmentbindings.yaml
appstudio-shared/config/crd/bases/appstudio.redhat.com_applicationsnapshots.yaml
appstudio-shared/config/crd/bases/appstudio.redhat.com_environments.yaml
appstudio-shared/manifests/appstudio-shared-customresourcedefinitions.yaml

Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
- Very cumbersome to type in the long API names when using CLI
- Adds shortnames for the shared APIs
Here is a summary:
`ApplicationSnapshotEnvironmentBinding` - `aseb`, `binding`
`ApplicationSnapshot` - `as`, `snapshot`
`Environment` - `env`
`ApplicationPromotionRun` - `apr`, `promotion`
N/A

Add short names for the shared APIs

---

appstudio-shared/config/crd/bases/appstudio.redhat.com_environments.yaml
appstudio-shared/manifests/appstudio-shared-customresourcedefinitions.yaml

Generate controller-gen manifests without which the step `Ensure that manifests are up-to-date` fails in the CI

Generate controller-gen manifests for appstudio-shared

---

backend/eventloop/eventlooptypes/eventlooptypes_suite_test.go
backend/eventloop/eventlooptypes/types.go
backend/eventloop/eventlooptypes/types_test.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go

This PR is to add the logic to avoid creating Operation for a resource, if it is already present in cluster, but waiting to be completed.
https://issues.redhat.com/browse/GITOPSRVCE-176
-  Modified CreateOperation() function to return existing operation if an In Progress Operation is already available in cluster.
- Added unit test cases.

Avoid creating duplicate Operations.

---

appstudio-shared/config/crd/bases/appstudio.redhat.com_environments.yaml
appstudio-shared/manifests/appstudio-shared-customresourcedefinitions.yaml
backend-shared/config/db/clusteruser_test.go
backend-shared/config/db/guardrow_test.go
tests-e2e/go.mod

Create database unit tests which guard against missing WHERE clauses of UPDATE/DELETE operations to the database (causing a global delete)
- The tests are added to one singular file called `guardrow_test.go` within `backend-shared/config/db` so that it's easy to test and does not come in the way of other unit tests of database operations.
https://issues.redhat.com/browse/GITOPSRVCE-173

DB unit tests to guard against missing WHERE clauses of UPDATE/DELETE operations

---

backend-shared/config/db/queries.go
backend-shared/config/db/queries_test.go
backend-shared/config/db/util/application_info_cache.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/preprocess_event_loop/preprocess_event_loop.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/workspace_resource_event_loop.go
backend/main.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
cluster-agent/main.go
manifests/managed-gitops-appstudio-controller-deployment.yaml
manifests/managed-gitops-backend-deployment.yaml
manifests/staging-cluster-resources/argo-cd.yaml
tests-e2e/core/managed_environment_test.go

- Fixing some issues seen on the AppStudio staging cluster:
- A 'too many connections' errors from PostgreSQL: fortunately we can use go-pg in-built connection sharing to solve this
- Appstudio-controller is OOM-ing, so we can increase the memory limits
- During stress unit tests, Argo CD is OOMing, so increase the memory limit of that
- Switch to using go-pg's existing connection pooling logic: one connection pool for 'verbose' logging, and one for without verbose logging
- Unit tests for above.
- Increase memory limits of appstudio-controller `Deployment` resource

Use go-pg's shared connection pool logic and update GitOps Service k8s manifests

---

backend-shared/config/db/applicationstates.go
backend-shared/config/db/clusteruser.go
cluster-agent/controllers/argoproj.io/application_controller.go
cluster-agent/controllers/argoproj.io/application_controller_test.go
cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache.go
cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache_test.go
cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache_types.go
cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
cluster-agent/controllers/util.go
cluster-agent/main.go

- Update Argo CD Application resource deletion logic to wait 2 minutes from the _current time_ for the application to delete, rather than from the deletion timestamp.
- Move application info cache to cluster-agent, and cleanup code
- Update DeleteArgoCDApplication logic to avoid Warning log

Move application info cache to cluster-agent, and cleanup code. Update DeleteArgoCDApplication logic to avoid Error log

---

backend-shared/apis/managed-gitops/v1alpha1/mocks/cr-client.go
backend-shared/apis/managed-gitops/v1alpha1/mocks/status-writer.go
backend-shared/apis/managed-gitops/v1alpha1/mocks/structs/gitopsdeployment.go
backend-shared/config/db/utils.go
backend-shared/config/db/utils_test.go
backend-shared/util/log.go
backend-shared/util/task_retry_loop.go
backend-shared/util/test_task_retry_loop_test.go
backend/condition/mocks/conditions.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/workspace_event_loop.go
backend/eventloop/workspace_resource_event_loop.go
backend/main.go
backend/util/createHook.go
cluster-agent/controllers/argoproj.io/namespace_reconciler.go
cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/repocred.go
cluster-agent/utils/argocd_login_credentials.go
cluster-agent/utils/mocks/ApplicationServiceClient.go
cluster-agent/utils/mocks/SessionServiceClient.go
cluster-agent/utils/mocks/SettingsServiceClient.go
cluster-agent/utils/mocks/VersionServiceClient.go

This is a cosmetic change to match the idiomatic way of writing Go >= 1.18 (thus it's breaking if you try to compile with previous versions). Generics aside, if the existing code uses `interface{}`, we can now replace it with `any` throughout, just as the **Go standard library has done**. So, what this PR is doing is something like this:
```go
func Print(args ...interface{}) {
```
can now be refactored very straightforwardly to:
```go
func Print(args ...any) {
```
_NOTE_: This doesn't mean the function is now turned into a generic, nor it has any other effect on it at all. The `any` shortcut it simply a **type alias** for `interface{}`, so Gophers can (and they should IMHO) to use the shorter name anywhere.
In brief, the new name for `interface{}` is `any`.
None

:recycle: Use any instead of interface{}

---

kcp/install-argocd.yaml
kcp/setup-kcp-cps.sh

Some of the changes that I missed when moving the manifest from my gist to managed-gitops repo in #197
- Remove liveness probes for all the components
- Add the missing protocol field
- Update KCP syncer to v0.7.8

Update argocd installation manifest for CPS

---

backend-shared/util/service_account.go
backend/eventloop/eventloop_test_util/eventloop_test_util.go

- Update the Secret/ServiceAccount creation logic to work with the logic that will work with newer versions of Kubernetes. I've tested it with both OpenShift 4.10 and OpenShift 4.11 (the two versions we support).
- Update the unit test logic which mocks  the ServiceAccount/Secret behaviour
- This removes the failover delay in the previous code (`wait.ErrWaitTimeout`), which would have increased the time to run the E2E test suite when running on OpenShift 4.11 and KCP.

Switch to defaulting to new Kubernetes behaviour for Secret/ServiceAccount

---

Makefile
kcp/ckcp/openshift_dev_setup.sh
kcp/ckcp/setup-ckcp-on-openshift.sh
kcp/install-argocd.yaml

Signed-off-by: Samyak Jain <samyak.jn11@gmail.com>
- This is continued work on setting up a local script that consumes the openshift cluster as a workload to KCP as well as KCP running within the same cluster. This concept was being followed by the pipeline service team as ckcp, and hence, in this script, we are an end user of ckcp to set up our local dev env and run e2e on it.
- The blocker from ckcp side: Release on 0.7 PR for the same is up here: https://github.com/openshift-pipelines/pipeline-service/pull/192.
- The PR https://github.com/redhat-appstudio/managed-gitops/pull/170 opened previously can be tweaked to work with local clusters such as kind k2d etc but we can't run our e2e test because it explicitly needs an openshift cluster.

Add local ckcp script for testing gitops service on kcp (Solves: #Gitopsrvc-158)

---

.ci/openshift-ci/Dockerfile

- Update the ci Dockerfile to match the kcp requirements, this PR is intended to add commands to install yq package in the ci's Dockerfile which is required by ckcp.
Ref: Check [logs](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31857/rehearse-31857-pull-ci-redhat-appstudio-managed-gitops-main-managed-gitops-e2e-tests-on-kcp/1565006131774885888#1:build-log.txt%3A37) from the release PR for the above requirement.

Update ci dockerfile to match the kcp requirements (Needed: #GITOPSRVC-187)

---

.ci/openshift-ci/Dockerfile

- Looks like https://github.com/openshift-pipelines/pipeline-service/pull/220 will be merged, so we need to add `argocd` as well.
- Use only `curl` for fetching binaries from the web.
Link to JIRA Story: [GITOPSRVCE-187](https://issues.redhat.com/browse/GITOPSRVCE-187)

Add ArgoCD CLI and use only curl

---

kcp/ckcp/setup-ckcp-on-openshift.sh

- Add a constraint to check, if the script is running in openshift ci env, if yes, then use k8s resource instead of docker utility.

Add a constraint to check if tests are running in ci

---

create-dev-env.sh
kcp/ckcp/setup-ckcp-on-openshift.sh
tests-e2e/core/applicationsnapshotenvironmentbinding_test.go

- In this PR, there is a check added in `create-dev-env.sh` to skip the check of postgresql-staging pods while running in kcp kubeconfig, as "pods" as a resource is not known at KCP; The actual pods are running in workload end, and hence, changes are made accordingly.

Add more constraints a/c to KCP to make openshift-ci happy (pt: 3/n)

---

create-dev-env.sh
kcp/ckcp/config.yaml
kcp/ckcp/openshift_dev_setup.sh
kcp/ckcp/setup-ckcp-on-openshift.sh

- Pulled out the latest changes from ckcp, integrated with the changes required for managed-gitops in `openshift-dev-env.sh` carefully, and tried maintaining the uniformity as much as possible
- Added a stable commit hash which is tested on clusterbot cluster which focuses on release-0.7; with every new release we need to update the script accordingly on ci as well as in our managed-gitops repo
- Added a better way for the cleanup function
To test the changes just run the `make kcp-test-local-e2e` target against a clusterbot cluster (v4.10/v4.11)

Update ckcp setup local script to reflect new changes from the repo (pt: 4/n)

---

kcp/ckcp/setup-ckcp-on-openshift.sh

In openshift-ci, the PostgreSQL database is not reachable for that we need to do port-forward, but kcp doesn't support it yet;
We are using `make devenv-k8s-e2e` for creating a testing environment. The long-term solution is to switch to more production-based testing, which we have opened the story for.
The hack, for now, is to check in the workload cluster where the Postgres is being deployed and port-froward from there, hence this PR is about that.
Logs here:
```
[36m09:21:32        cluster-agent | [mgo: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
[36m09:21:32        cluster-agent | [mgo: downloading github.com/go-git/go-billy/v5 v5.0.0
[32m09:21:32              backend | [mgo vet ./...
[36m09:21:34        cluster-agent | [mgo vet ./...
[35m09:22:05 …
```

hack: port-forward postgres db from the workload cluster until kcp supports or we migrate to release testing manner

---

kcp/ckcp/setup-ckcp-on-openshift.sh

- Let CI pod use its local kubeconfig, instead of explicitly defining "" as default
- Slack Thread for reference, [here](https://coreos.slack.com/archives/CBN38N3MW/p1662790897362269)

Let ci pod use it's local kubeconfig automatically

---

tests-e2e/core/applicationpromotionrun_controller_test.go
tests-e2e/fixture/promotionrun/fixture.go

A E2E test is failing due to race condition, hence temporarily dropping it to unblock other PRs.

Skip one E2E test for OpenShift CI.

---

tests-e2e/core/applicationpromotionrun_controller_test.go

- Skipping applicationpromotionrun_controller_test.go in KCP to unblock story 187

Skipping applicationpromotionrun_controller_test.go in KCP to unblock story 187

---

kcp/utils.sh
kcp/virtual-workspace.sh

- Create a script to create service provider and user workspaces
- Create APIExports and APISchemas in the service workspace
- Create APIBindings in the user workspace
- Install Argo CD and GitOps Service in the service workspace
- Move the common functions to utils.sh to avoid duplicates.
https://issues.redhat.com/browse/GITOPSRVCE-207
1. Login to an OCP cluster
2. Login to CPS and set the path to CPS KUBECONFIG and run the script in the root directory
```shell
$ export CPS_KUBECONFIG=<path-to-CPS-kubeconfig>
$ ./kcp/virtual-workspace.sh
```
3.  Verify if the GitOps service controllers are up and running
4. Copy the KUBECONFIG to a different location and open a new tab. We don't want to change the KUBECONFIG that is referenced by the GitOps service running in the service provider …

Setup service provider and user workspace 

---

manifests/kcp-resources/argocd-cluster-config.yaml
manifests/kcp-resources/kube-system-namespace.yaml
manifests/kustomization.yaml

- a kustomize YAML file that points to all the manifests in our repository that are responsible for deploying to KCP
- For now, the kustomisation contains, APIExoorts, APIResourceSchema, Namespace creation for `kube-system`, `gitops-service-argocd`, RBAC's, Workloads, Routes, and a hack for `in-cluster-config` secret mount.
- We have scripts ready for testing against local kcp (ckcp) or using kcp service (CPS), both of the scripts were using some hacks in order to work ArgoCD with sync targets. One of which is included in the kustomisation file which is mounting a secret for `argocd-cluster-config`, located [here](https://github.com/samyak-jn/managed-gitops/blob/kustomize-kcp-manifests-for-gitops/manifests/kcp-resources/argocd-cluster-config.yaml). For another …

Kustomize overlay with GitOps Service KCP Manifests (Solves: #GITOPSRVC-209)

---

Makefile

Fixes the e2e:
```
COMMON_IMAGE=quay.io/redhat-appstudio/gitops-service:latest envsubst < /go/src/github.com/redhat-appstudio/managed-gitops/manifests/controller-deployments/managed-gitops-appstudio-controller-deployment.yaml | kubectl apply -f -
/bin/sh: /go/src/github.com/redhat-appstudio/managed-gitops/manifests/controller-deployments/managed-gitops-appstudio-controller-deployment.yaml: No such file or directory
error: no objects passed to apply
make: *** [deploy-appstudio-controller] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-10-17T09:03:17Z"}
error: failed …
```

Fixes E2E: AppStudio controller manifest PATH

---

Makefile
kcp/kcp-e2e/setup-ws-e2e.sh
kcp/kcp-e2e/start-ws-e2e.sh
kcp/utils.sh
kcp/virtual-workspace.sh
utilities/yamllint.yaml

-  The GitOps Service E2E tests assume that the GitOps Service, Argo CD, and User APIs, are running on the same cluster (in the same Kubernetes API server/config/context). This is because we were supporting the deployment topology of the app studio staging cluster/our local dev environments.
- However, that is not the case with KCP virtual workspaces. When running with KCP virtual workspaces, there will actually be two separate KCP workspaces: The service provider workspace (where gitops and argocd will be installed and running) and the user workspace (where the user will create an APIBinding for accessing the service)
- This PR extends the work done in 207 by setting up scripts to add make targets for E2E testing on KCP v ws.

Setup make targets for E2E testing on KCP virtual workspaces (Solves: #GITOPSRVC-212)

---

backend-shared/config/db/apicrtodatabasemapping.go
backend-shared/config/db/operations.go
backend-shared/config/db/queries.go
backend-shared/config/db/types.go
backend-shared/config/db/utils.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/workspace_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
utilities/db-migration/go.mod
utilities/db-migration/go.sum

- Cleaning up old technical debt by:
- Converting some strings to be typed constants 
- Adding a sanity test for detecting changes to name field of Application row, when processing GitOpsDeployment events
- Removing outdated TODOs
- Moving TODOs that are still relevant to a more appropriate story #

Convert strings to typed constants, add a sanity test, and clean up old TODOs

---

cluster-agent/utils/argocd_create.go
kcp/utils.sh
kcp/virtual-workspace.sh
manifests/kcp/argocd/install-argocd.yaml
manifests/staging-cluster-resources/argo-cd.yaml

- Add resource exclusions to Argo CD CR and argocd-cm config map
- Update syncer image to v0.9.1 and fix the script
https://issues.redhat.com/browse/GITOPSRVCE-242

Exclude *.kcp.dev resources from Argo CD watch list

---

kcp/utils.sh
kcp/virtual-workspace.sh

- Create SyncTarget for a user workspace.
- Currently, we check if a SyncTarget is ready by waiting until the deployment is in the `Ready` state. But the APIs may not be synced yet leading to an error when applying argocd resources. Add a step to check whether the required CRDs are synced by the Syncer.

Check if the APIs are synced in a workspace

---

.github/workflows/static.yml
backend/routes/webhooks/webhooks.go
cluster-agent/utils/retrieve_metrics.go
tests-e2e/core/managed_environment_test.go

- Bump golangci-lint version to keep up
- Had to replace the deprecated `io/ioutils` packages (since Go 1.16) with either `io` or `os`.
None

ci: Bump golangci

---

kcp/ckcp/config.yaml
kcp/ckcp/openshift_dev_setup.sh
kcp/ckcp/setup-ckcp-on-openshift.sh

For now, the CI for KCP-based e2e is running on v0.7.0, and since the setup, we have two major KCP releases that CKCP has also adopted.
Thus, to keep up and mitigate the differences with the CKCP we need to upgrade the version to the latest as shipped by the pipelines team. This might also involve fixing some issues with the script.

Upgrade & Fix CKCP to v0.9.0 (Solves: #GITOPSRVCE-252)

---

kcp/kcp-e2e/setup-ws-e2e.sh
tests-e2e/core/argocd_application_test.go
tests-e2e/core/argocd_instance_test.go
tests-e2e/core/core_suite_test.go
tests-e2e/core/gitopsdeployment_resource_test.go
tests-e2e/core/gitopsdeployment_status_test.go
tests-e2e/core/gitopsdeployment_test.go
tests-e2e/core/managed_environment_test.go
tests-e2e/core/promotionrun_controller_test.go
tests-e2e/core/simple_test.go
tests-e2e/core/snapshotenvironmentbinding_test.go
tests-e2e/fixture/application/fixture.go
tests-e2e/fixture/binding/fixture.go
tests-e2e/fixture/fixture.go
tests-e2e/fixture/gitopsdeployment/fixture.go
tests-e2e/fixture/k8s/fixture.go
tests-e2e/fixture/promotionrun/fixture.go

-  new `EnsureCleanSlateKCPVirtualWorkspace` function (based on the existing EnsureCleanSlate function), and updating the tests to call this function when running on KCP virtual workspace.
```
// EnsureCleanSlateKCPVirtualWorkspace should be called before every E2E tests:
// it ensures that in KCP Virtual workspace the state of the GitOpsServiceE2ENamespace namespace
//	(and other resources on the cluster) is reset to scratch before each test, including:
// - In user workspace, the function will:
// 		- Deleting any old namespaces that exists within the user-workspace
// 		- Deleting any cluster role/rolebindings existing within the user-workspace
// 		// EnsureCleanSlateKCPVirtualWorkspace should be called before every E2E tests:
// it ensures that in KCP Virtual workspace the state of …
```

Update E2E test harness/code to work with KCP virtual workspaces (Solves: #GITOPSRVCE-213)

---

backend-shared/util/task_retry_loop.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/repocred.go
cluster-agent/utils/argocd_terminate_app_command.go

- Ensure that only one operation is running at a time for a particular resource (Application/SyncOperation/etc)
- Sugar: `true/false` -> `shouldRetryTrue/False` for functions returning a should retry value 
- Add processing of SyncOperation resource, which will cause Argo CD to do a manual sync (or to terminate a manual sync), based on the contents of the SyncOperation resource in the DB.
- Unit/E2E tests to be worked on elsewhere, this is being pushed to unblock team members

Add support for syncing/terminating sync of an Argo CD Application to cluster-agent

---

appstudio-controller/config/rbac/role.yaml
appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
manifests/appstudio-controller-rbac/appstudio-controller-rbac.yaml

- This PR add secrets resources to the appstudio controller. The controller right now is not able to list the environment secrets in the cluster.

Add secrets resources to the appstudio controller

---

appstudio-controller/config/rbac/role.yaml
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller_test.go
tests-e2e/core/promotionrun_controller_seb_test.go
tests-e2e/fixture/fixture.go

- Updated the PromotionRun reconciliation to always create a SnapshotEnvironmentBinding (SEB) for the target application/environment, if that SEB doesn't already exist.
- Created unit tests for the new function
- Created e2e tests for the new function
https://issues.redhat.com/browse/GITOPSRVCE-239

PromotionRun should create a SnapshotEnvironmentBinding (for app/env) if it doesn't already exist

---

.github/workflows/schema-sync.yml
.github/workflows/static.yml

Main reason: it gives us the option to use Go Workspaces in the GitHub Actions as well
Bumps [actions/setup-go](https://github.com/actions/setup-go) from 3.2.0 to 3.4.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/actions/setup-go/releases">actions/setup-go's releases</a>.</em></p>
<blockquote>
<h2>Add support for go.work and pass the token input through on GHES</h2>
<p>In scope of this release we added <a href="https://github-redirect.dependabot.com/actions/setup-go/pull/283">support for go.work file to pass it in go-version-file input</a>.</p>
<pre lang="yaml"><code>steps:
- uses: actions/checkout@v3
- uses: actions/setup-go@v3
with:
go-version-file: go.work
- run: go run hello.go
</code></pre>
<p>Besides, we added support to <a …

chore: Bump setup-go to v3.4.0

---

backend-shared/config/db/gitopsengineinstance.go
backend-shared/config/db/repo_cred.go
backend-shared/config/db/repo_cred_test.go
backend-shared/config/db/types.go
backend-shared/config/db/util/utils.go
backend-shared/util/operations/types.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
backend/eventloop/workspace_resource_event_loop.go
examples/m10-demo/README.md
manifests/staging-cluster-resources/argo-cd.yaml
tests-e2e/core/privaterepo_test.go
tests-e2e/fixture/k8s/fixture.go

- Processing logic for Backend controller that is responsible for acting upon a  GitOpsDeploymentRepositoryCredential CR.
https://issues.redhat.com/browse/GITOPSRVCE-96
Instruction for the reviewer:
- There were a number of problems with logging. That is why you will find many replacements of `log` and `logger` into `l`.
- The main that has he logic is the `sharedresourceloop.go`
- The test file is the `sharedresourceloop_test.go` the last `It` context.
- What is missing is that the function `internalProcessMessage_ReconcileRepositoryCredential` is not getting triggered by the backend controller when you create a real `GitOpsDeploymentRepositoryCredential` CR. Most likely this is related to the code relocation from the file [application_event_runner_deployments.go](https://github.com/redha …

Implement GitOpsDeploymentRepositoryCredential API CR in GitOps Service

---

backend-shared/config/db/deploymenttoapplicationmapping.go
backend-shared/config/db/deploymenttoapplicationmapping_test.go
backend-shared/config/db/queries.go
backend/eventloop/db_reconciler test.go
backend/eventloop/db_reconciler.go
backend/eventloop/db_reconciler_test.go
backend/go.mod
backend/main.go
utilities/db-migration/go.mod
utilities/db-migration/go.sum

This PR is to add a Periodic job (DatabaseReconciler) which will run in background to detect such DeploymentToApplicationMappings entries which don't have respective GitOpsDeployment CR present in cluster and delete all related entries from DB.
https://issues.redhat.com/browse/GITOPSRVCE-286

Periodic job to clean up orphan DeploymentToApplicationMappings.

---

backend-shared/config/db/queries.go
backend-shared/config/db/syncoperation.go
backend-shared/config/db/syncoperation_test.go
backend-shared/config/db/types.go
backend-shared/util/operations/types.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/application_event_loop/application_event_runner_syncruns_test.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/workspace_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
cluster-agent/main.go
cluster-agent/utils/argocd_login_credentials.go
cluster-agent/utils/argocd_sync_command.go

- Refactored `applicationEventRunner_handleSyncRunModifiedInternal()` and created separate methods to handle creation, updation and deletion of SyncRun CRs
- Resolved TODOs for [GITOPSRVCE-166](https://issues.redhat.com//browse/GITOPSRVCE-166)
- Added unit tests in the backend and cluster agent
- Fixed bugs around goroutine shutdown 
https://issues.redhat.com/browse/GITOPSRVCE-166
https://issues.redhat.com/browse/GITOPSRVCE-82

Refactor and add unit tests for GitOpsDeploymentSyncRun 

---

backend-shared/util/operations/types.go
backend-shared/util/task_retry_loop.go
backend/eventloop/application_event_loop/application_event_loop.go
backend/eventloop/application_event_loop/application_event_loop_test.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/event_loop_suite_test.go
backend/eventloop/eventlooptypes/types.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/workspace_event_loop.go
backend/eventloop/workspace_event_loop_test.go
backend/eventloop/workspace_resource_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
tests-e2e/core/gitopsdeployment_test.go
utilities/db-migration/go.mod
utilities/db-migration/go.sum

- This PR fixes a bug where events would stop being handled for `GitOpsDeployment`s, due to the goroutine responsible for handling them closing too early.
- The Goroutine responsible for handling them, the application event loop, would terminate when the GitOpsDeployment resources was deleted.
- However, the workspace event loop would not know that the application event loop has closed, and so the workspace event loop would keep trying to send events to the app event loop.
- This would block the workspace event loop, as it was trying to send a message on a channel with no receiver.
- This was an unforeseen consequence of a [previous bug fix](https://github.com/redhat-appstudio/managed-gitops/pull/249).
Fixes:
- Application Event Loop will now receive/send …

Fix application event loop closing too quickly after a GitOpsDeployment is deleted, and workspace event loop not starting a new one

---

backend-shared/util/tests/types_test_util.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/eventlooptypes/types_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/workspace_event_loop_test.go
backend/eventloop/workspace_resource_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
cluster-agent/utils/argocd_login_credentials_test.go
cluster-agent/utils/argocd_sync_command.go
cluster-agent/utils/argocd_sync_command_test.go
cluster-agent/utils/argocd_terminate_app_command_test.go

- When creating a Namespace, you should not specify the .metadata.Namespace field, e.g.
```yaml
kind: Namespace
metadata:
name: my-namespce
namespace: my-namespace  # this field is not require,d or correct, for Namespaces.
```
- Namespaces are not namespace-scoped, and thus should not have a `namespace:` field.
- That one shouldn't do this is pretty obvious, but there were a number of places in the code (primarily in unit tests), where we WERE doing this, and relying on this field
- This PR removes references to the field, and updates tests as needed.

Remove all uses of metadata.Namespace field of Namespace resources

---

backend/config/default/manager_auth_proxy_patch.yaml
backend/config/manager/manager.yaml

- Restore the controller limits to their original values: they were unintentionally reduced by the latest manifest update.

Patch backend component on stonesoup cluster: restore controller limits to original values

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeployment_types.go
backend-shared/config/crd/bases/managed-gitops.redhat.com_gitopsdeployments.yaml
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns_test.go
backend/eventloop/application_event_loop/application_event_runner_test.go
tests-e2e/core/gitopsdeployment_status_test.go

- Removed omitempty from path field
- Setting error in .status.conditions field of GitopsDeployment CR when spec.source.path field is empty  or '/'
- Some minor tweaks in syncError condition(not related to this PR)
- Unit tests and e2e tests
https://issues.redhat.com/browse/GITOPSRVCE-307

Error is set in .status.conditions field when path field is empty

---

backend-shared/util/gitopserrors/gitops_errors.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go

- Updated the code that sets the connection condition status to ensure the user messages don't expose internal details

Sanitize messages for managed environment connection status

---

backend/metrics/metrics.go
backend/metrics/metrics_test.go

- Change `AddOrUpdateGitOpsDeployment()` to check if an entry for the deployment already exists before setting its error condition to `false`.

Fix continual increment of deployment failures metric

---

manifests/grafana/Gitops-combined.json
manifests/grafana/gitops-dashboard.json

- Add initial Grafana dashboard showing the active and failed gitops deployments

Add initial Grafana dashboard

---

manifests/overlays/appstudio-staging-cluster/prometheus/appstudio-controller/kustomization.yaml
manifests/overlays/appstudio-staging-cluster/prometheus/backend/kustomization.yaml
manifests/overlays/appstudio-staging-cluster/prometheus/cluster-agent/kustomization.yaml

- Disable the Stonesoup-cluster-specific ServiceMonitors, and instead move them to infra-deployments, as requested.

Disable Stonesoup-specific ServiceMonitors, move them to infra-deployments

---

appstudio-controller/config/rbac/kustomization.yaml
backend/config/rbac/kustomization.yaml
cluster-agent/config/rbac/kustomization.yaml
manifests/overlays/appstudio-staging-cluster/kustomization.yaml

- Add RBAC to allow controllers to create TokenReviews (this was failing on Stonesoup cluster to missing roles/rolebindings)
- Add missing appstudio-controller deployment patch (this was inadvertently excluded).

Add RBAC to allow controllers to create TokenReviews, add missing appstudio-controller deployment patch

---

.github/workflows/sync-branch.yml

For the nightly build of the service, we are using the service-first branch to solve the issue with local dependency.
This github action will sync the 'main' and 'service-first' branch by creating auto PRs whenever a new push is made to the main branch
https://issues.redhat.com/browse/GITOPSRVCE-274

Sync main and service-first branch using Github Action

---

backend/config/manager/manager.yaml
cluster-agent/config/manager/manager.yaml
manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
manifests/overlays/appstudio-staging-cluster/cluster-agent-deployment-patch.yaml

- Update request/limits for backend/cluster-agent components when running on Stonesoup
- Reduce requests/limits when not running on Stonesoup (e.g. on dev's machines)

Update request/limits for backend and cluster-agent components, for Stonesoup

---

Makefile
appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
appstudio-controller/go.mod
appstudio-controller/go.sum
manifests/base/crd/kustomization.yaml
tests-e2e/core/managed_environment_test.go
tests-e2e/fixture/managedenvironment/fixture.go
tests-e2e/go.mod
tests-e2e/go.sum

- Updated allowInsecureSkipTLSVerify field of GitOpsDeploymentManagedEnvironment with allowInsecureSkipTLSVerify field of App-studio Environment API
- Updated Unit tests
- Added E2E test
https://issues.redhat.com/browse/GITOPSRVCE-334

Add allowInsecureSkipTLSVerify field in Environment API

---

appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go

- Skip reconciliation of events for resources in Namespaces that are being deleted
- We want to avoid the case where the GitOps Service/Argo CD are keeping the Namespace from being deleted by creating/recreating resources as they are deleted.

Skip reconciliation of events for resources in Namespaces that are being deleted

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeployment_types.go
backend-shared/config/crd/bases/managed-gitops.redhat.com_gitopsdeployments.yaml

- Add kubebuilder print column tags to show sync and health status columns
```shell
$ kubectl get gitopsdeployments.managed-gitops.redhat.com -A
NAMESPACE   NAME          SYNC STATUS   HEALTH STATUS
jane        gitops-depl   Synced        Healthy
jgw         gitops-depl   Synced        Degraded
```

Add printcolumn tags for sync and health status

---

appstudio-controller/controllers/appstudio.redhat.com/application_controller.go
tests-e2e/core/appstudio_application_test.go

- Removed GitOpsDeployment creation logic for Applications in ApplicationReconciler
- Skipped e2e test related to this
https://issues.redhat.com/browse/GITOPSRVCE-357

Re-removing the gitOpsDeployment creation logic for Applications

---

tests-e2e/core/snapshotenvironmentbinding_test.go

- Fix a race condition I noticed in the SnapshotEnvironmentBinding tests: we should wait for the GitOpsDeployment to exist (and not exist), rather than assuming it that it will be created quickly.

Fix test race condition in SnapshotEnvironmentBinding E2E test

---

appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller_test.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
tests-e2e/core/managed_environment_test.go
tests-e2e/core/promotionrun_controller_test.go
tests-e2e/core/snapshotenvironmentbinding_test.go

Remove Type field from Unit tests and e2e tests as it is not required
Here is the PR in Application API where I have added omitempty for Type field in Environment Spec
https://github.com/redhat-appstudio/application-api/pull/28 
https://issues.redhat.com/browse/GITOPSRVCE-356

Remove Type field from Unit tests and e2e tests

---

backend/routes/webhooks/webhooks.go
cluster-agent/utils/argocd_login_credentials.go

- gosec checks are failing because err is not handled inside defer

Fix gosec issues by handling error in defer

---

manifests/base/monitoring/grafana-dashboards/stonesoup-new/gitops-dashboard.json
manifests/base/monitoring/grafana-dashboards/stonesoup-new/kustomization.yaml

- The current stonesoup dashboard JSON isn't working (for non-obvious reasons), so instead trying a JSON blob exported from the Stonesoup staging cluster.

Add an exported version of the stonesoup dashboard from Stonesoup Staging cluster

---

manifests/base/crd/base/kustomization.yaml
manifests/base/crd/overlays/local-dev/kustomization.yaml
manifests/base/crd/overlays/stonesoup/kustomization.yaml
manifests/overlays/k8s-env/kustomization.yaml
manifests/overlays/local-dev-env-with-k8s-db/kustomization.yaml
manifests/overlays/local-dev-env/kustomization.yaml
manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/cluster-agent-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/kustomization.yaml

- Add a new overlay specific to deploying to the app-interface member cluster, including reading from RDS secret
- Refactor CRDs: in the AppStudio/Stonesoup case, we shouldn't be deploying the application-api-defined CRDs
- [GITOPSRVCE-401](https://issues.redhat.com/browse/GITOPSRVCE-401)
- [GITOPSRVCE-402](https://issues.redhat.com/browse/GITOPSRVCE-402)

Add support for RDS on app-interface member cluster, and refactor CRD YAML to remove application-api CRs

---

manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
utilities/init-container/hotfix/hotfix.go

- The Stonesoup E2E tests are currently failing on our latest code drop, as the init container code (introduced to fix a bug on staging as part of https://github.com/redhat-appstudio/managed-gitops/pull/287) is returning an error if the database has not been initialized (which is always the case when the E2E tests first run, as part of a PR)
- We can detect if the database has not been initialized by using the exact error code returned by postgresql
- In this case, the init container could should return 0, and allow the backend controller to initialize the database.

KubernetesToDBResourceMapping patch should exit with zero error code if DB has not been initialized

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeployment_types.go
backend-shared/db/utils.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go
tests-e2e/core/gitopsdeployment_test.go
tests-e2e/fixture/gitopsdeployment/fixture.go
tests-e2e/fixture/k8s/fixture.go

- Adds support for the deletion finalizer `resources-finalizer.managed-gitops.redhat.com`. 
- In the presence of the finalizer, GitOpsDeployment will wait for the deletion of all the child resources. Once all the dependencies are removed, the backend will remove the deletion finalizer and the GitOpsDeployment CR will be deleted.
- Unit tests and e2e tests 
https://issues.redhat.com/browse/GITOPSRVCE-360

Add support for resource cleanup finalizer for GitOpsDeployment 

---

utilities/upgrade-service/README.md
utilities/upgrade-service/install-upgrade.sh

The PR adds a script for users to be able to install or upgrade Managed Gitops Service to a specific version. The version of managed-service is identified using the image passed to the script using `-i` flag.
The script provide 2 optional flags for users. If no flag is provided, the script will try to fetch `quay.io/redhat-appstudio/gitops-service:latest` as the default image. The available options are:
- `-i` : provide gitops service image (default: `quay.io/${QUAY_USERNAME}/gitops-service:latest`, QUAY_USERNAME = `redhat-appstudio`)
- `-u`: provide QUAY registry username (default: `redhat-appstudio`). This will replace the value of QUAY_USERNAME in `quay.io/${QUAY_USERNAME}/gitops-service:latest`.
[GITOPSRVCE-316](https://issues.redhat.com/browse/GITOPSRVCE-316)
We are working on …

feat: add script to install/upgrade managed service

---

appstudio-controller/Makefile

Creating a separate PR for this.
See https://issues.redhat.com/browse/GITOPSRVCE-433
I tested the change on both Mac Arm64 and Fedora 37.
https://issues.redhat.com/browse/GITOPSRVCE-433

appstudio-controller tests fail on Mac Arm64 (#433)

---

backend-shared/db/util/utils.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/main.go

- Minor cleanup: 
- Rename `internalDetermineGitOpsEngineInstance` to make it's purpose more
- Remove managedEnvironment as an input to `internalDetermineGitOpsEngineInstance` API: using a ManagedEnv as an input into what GitOpsEngineInstance to use is an idea that is not fully baked.
- Remove uses of `GetOrCreateManagedEnvironmentByNamespaceUID` that are no longer needed, base on above.
- Add additional comment explaining why `GetOrCreateManagedEnvironmentByNamespaceUID` exists

Remove unnecessary uses of GetOrCreateManagedEnvironmentByNamespaceUID, and add additional comments around its purpose

---

manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
utilities/init-container/main.go

- See [GITOPSRVCE-449](https://issues.redhat.com//browse/GITOPSRVCE-449) for details of the problem, and the fix.
- This fix detects if the database contains the problematic field values, and if so, updates them, before the GitOps Service backend container starts, via an init container.
- If the problematic field values are not detected, this is a no-op.

GITOPSRVCE-449: update known bad values on stonesoup clusters, via init-container

---

appstudio-controller/config/default/manager_webhook_patch.yaml
appstudio-controller/config/manager/manager.yaml
appstudio-controller/config/webhook/manifests.yaml
appstudio-controller/go.mod
appstudio-controller/go.sum
appstudio-controller/main.go
manifests/base/crd/overlays/local-dev/kustomization.yaml
manifests/overlays/appstudio-staging-cluster/kustomization.yaml
manifests/overlays/k8s-env/kustomization.yaml
tests-e2e/core/promotionrun_controller_test.go
tests-e2e/core/webhook_test.go
tests-e2e/go.mod
tests-e2e/go.sum

This PR enables Webhooks which are implemented in `application-api` to avoid changes in immutable fields.
PR to add webhooks in application-api:- https://github.com/redhat-appstudio/application-api/pull/26
**Note**
This PR also removes few existing test cases which are updating Spec fields of CR and now that is not allowed by Webhooks.
https://issues.redhat.com/browse/GITOPSRVCE-211

Webhook implementation for CRs.

---

appstudio-controller/config/default-no-prometheus/kustomization.yaml
manifests/overlays/appstudio-staging-cluster/kustomization.yaml
manifests/overlays/stonesoup-member-cluster/kustomization.yaml

- The appstudio-staging-cluster overlay is currently failing to build when generated via kustomize
- Solution is to prevent dual definition of prometheus manifests

Fix kustomize error in appstudio-staging-cluster overlay

---

backend-shared/db/application.go
backend-shared/db/managedenvironment.go
backend-shared/db/queries.go
backend-shared/db/repo_cred.go
backend-shared/db/syncoperation.go
backend-shared/db/unreliable_db_client.go
backend/eventloop/db_reconciler.go
backend/eventloop/db_reconciler_test.go
backend/go.mod

This PR is to add a logic which will periodically iterate through `Applications` table and delete entry if it does not have entry in `DeploymentToApplicationMapping`, same is for `ManagedEnvironment`, `RepositoryCredentials`, `SyncOperation` if they dont have entry in `APICRToDatabaseMapping`
https://issues.redhat.com/browse/GITOPSRVCE-350
- Introduced new functions for `ManagedEnvironment`, `RepositoryCredentials`, `SyncOperation` to read data in batches.
- Added logic to go through `Application`, `RepositoryCredential`, `SyncOperation`, `ManagedEnvironment` tables and delete orphaned entries.
- Grouped functions according to their use cases.
- Introduces unit test cases for new logic.
- Renamed few functions
```
deplToAppMappingDbReconcile -> cleanOrphanedEntriesfromTable_DTAM …
```

Periodic clean-up for orphaned DB entries.

---

backend/eventloop/db_reconciler.go
backend/eventloop/db_reconciler_test.go

- Temporarily disable deletion of ManagedEnviroment resources by database reconciler.

Temporarily disable deletion of ManagedEnviroment resources by database reconciler.

---

manifests/base/monitoring/grafana-dashboards/managed-gitops/gitops-dashboard.json
manifests/base/monitoring/grafana-dashboards/stonesoup/gitops-dashboard.json

- Added panels to display the health and sync status of Argo CD applications managed by gitops service.

Add Argo CD application status to gitops dashboard

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go
manifests/overlays/stonesoup-member-cluster/appstudio-controller-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/backend-deployment-patch.yaml
manifests/overlays/stonesoup-member-cluster/cluster-agent-deployment-patch.yaml

- Disable logging of API Resource changes when the only thing that has changed is the GitOpsDeployment.status field: there's no audit purpose to us logging these.
- Disable logging of SnapshotEnvironmentBinding Reconciles when the resource has not changed after Reconcile.
- Switch Stonesoup cluster to run at INFO level (when we have a staging server, we can switch _it_ to run at DEBUG, and also look at reducing/customizing the verbosity of DEBUG)

Reduce log verbosity of backend and appstudio-controller components

---

Makefile
Procfile.chaos
appstudio-controller/Makefile
backend/Makefile
cluster-agent/Makefile
docs/chaos-engineering.md
tests-e2e/fixture/fixture.go
utilities/random-kill.sh

- This PR adds functionality that simulates the GitOps Service controllers randomly restarting every ~30 seconds.
- This also adds documentation for the other chaos engineering code that went in as part of earlier stories.
- I also fixed an intermittent E2E test bug, where the GitOpsDeployment finalizers added by the resource-deletion finalizer are not properly cleaned up by the EnsureCleanSlate-based test fixture.

Chaos Engineering: simulate random restarts of controller processes

---

backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_deployments_test.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/application_event_loop/application_event_runner_syncruns_test.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/application_event_loop/metrics_test.go

- The `getK8sClientForGitOpsEngineInstance` field has long since been deprecated by the newer `k8sClientFactory` field.
- The `k8sClientFactory` interface is a superset of the `getK8sClientForGitOpsEngineInstance`  functionality
- This deprecated field likely should have been removed as part of my original ManagedEnvironment PR, but better late than never :grinning:

chore: remove deprecated getK8sClientForGitopsEngineInstance function

---

.gitignore
backend-shared/db/kubernetesresourcetodbresourcemapping.go
backend-shared/db/queries.go
backend-shared/db/unreliable_db_client.go
backend/eventloop/db_reconciler.go
backend/eventloop/db_reconciler_test.go

- I've updated the ManagedEnvironment cleanup logic: it should only allow deletion of a ManagedEnvironment if there is no corresponding K8sToDBResourceMapping that ALSO points to the ManagedEnvironment
- New unit test to verify the new behaviour
- Add a 'skipDelay' parameter to functions in db_reconciler_test.go, in order to reduce the time it takes to run these functions when run as part of unit tests. This significantly reduces the length of time it takes to run the backend tests.
- Rename appRowBatchSize => rowBatchSize

Re-enable deletion of ManagedEnvironments, as long as no K8sToDBResourceMapping points to it

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go

- In appstudio-controller on live cluster,  we're seeing SnapshotEnvironmentBinding controller logs about ~1 per second, related to updates to SnapshotEnvironmentBinding resource.
- However, in most cases, these logs are only updates to the `.status` field of the SnapshotEnvironmentBinding, for which there is little value in logging (e.g. for auditing purposes).
- We can thus remove that log statement for this case.

Remove unnecessary logging of SnapshotEnvBinding .status changes

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentmanagedenvironment_types.go
backend-shared/util/log.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
tests-e2e/core/managed_environment_status_test.go
tests-e2e/core/operation_namespace_test.go

- This PR has no logic changes, just refactoring of existing code as follows:
- Rather than calling `updateManagedEnvironmentConnectionStatus` at a bunch of places in the code, instead we should just return a struct, `connectionInitializedCondition`, from functions, and set the status in a single central location `internalProcessMessage_ReconcileSharedManagedEnv`.
- Utility functions for creating various conditions, to reduce code duplication
- Moving the conditions into backend-shared, so they can be consumed by other components.

Refactor backend GitOpsDeployManagedEnvironment status update code

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentmanagedenvironment_types.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/workspace_event_loop_test.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
tests-e2e/core/managed_environment_status_test.go
tests-e2e/core/managed_environment_test.go

- `updateGenerateExpectedClusterSecret` with the new logic
- Add unit tests to verify the functionality (plus other related functionality)
- E2E tests will be handled by the other story
Done: ~Merge #397 first, before this PR.~

Add managedEnvironment query parameter to the Argo CD cluster secret

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentmanagedenvironment_types.go
backend-shared/config/crd/bases/managed-gitops.redhat.com_gitopsdeploymentmanagedenvironments.yaml
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
tests-e2e/core/managed_environment_status_test.go
tests-e2e/core/managed_environment_test.go
tests-e2e/fixture/k8s/fixture.go

Description:
x--- @jgwest, the e2e tests aren't checked in. But you can run your test and add the boolean flag. Note, the validation of the cluster credentials failed however, even though the test passes. ---x
Update: e2e tests are now checked in and validation using the cluster credentials now pass.
Link to JIRA Story (if applicable):
https://issues.redhat.com/browse/GITOPSRVCE-328

Add new service account behaviour to ManagedEnvironment CR (#328) 

---

appstudio-controller/main.go
backend-shared/util/profiling.go
backend/main.go
cluster-agent/main.go
docs/profiling.md

- Add support for serving profiles for GitOps service controllers. The generated profiles could either be used by `go tool pprof` or a continuous profiling tool for debugging performance issues.
1. Start the controllers by enabling profiling
`ENABLE_PROFILING=true make start`
2. Go to locahost:6060/6061/6062 to verify the profiles

Support for pprof profiling

---

Makefile
tests-e2e/Makefile

Update the 'check-backward-compatibility' target to use 'go test' instead of 'ginkgo focus' as Ginkgo is not installed on OpenshiftCI
https://issues.redhat.com/browse/GITOPSRVCE-453

Update backward compatibility test to use 'go test' instead of ginkgo 

---

manifests/base/monitoring/grafana-dashboards/managed-gitops/gitops-dashboard.json
manifests/base/monitoring/grafana-dashboards/stonesoup/gitops-dashboard.json

- Exposed below mentioned metrics from appstudio-controller
-  workqueue_work_duration_seconds_bucket
-  workqueue_work_duration_seconds_count
-  workqueue_depth
-  workqueue_unfinished_work_seconds
-  controller_runtime_reconcile_errors_total
-  controller_runtime_reconcile_total
-  controller_runtime_reconcile_time_seconds_bucket
-  controller_runtime_reconcile_time_seconds_count
- controller_runtime_max_concurrent_reconciles
https://issues.redhat.com/browse/GITOPSRVCE-444

Expose controller-runtime's metrics for for appstudio-controller

---

backend/controllers/managed-gitops/secret_controller.go
backend/controllers/managed-gitops/secret_controller_test.go
backend/eventloop/application_event_loop/application_event_loop.go
backend/eventloop/workspace_event_loop.go
utilities/load-test/gitops-service/gitops_service_test.go
utilities/load-test/gitops-service/suite_test.go
utilities/load-test/go.mod

- Instead of creating a new client whenever the `startNewStatusUpdateTimer()` is invoked, we reuse an existing client passed from the workspace event loop.  Thereby we can avoid multiple client objects escaping to the heap.
- Use a predicate in the secrets controllers to filter secrets of type: managed-environment.
- Test to verify memory usage.
https://issues.redhat.com/browse/GITOPSRVCE-508

Reduce memory usage by reusing the client from the workspace eventloop

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentmanagedenvironment_types.go
backend-shared/config/crd/bases/managed-gitops.redhat.com_gitopsdeploymentmanagedenvironments.yaml
backend/eventloop/workspace_resource_event_loop.go
docs/api.md
docs/components.md

- No functional code changes, just comments and doc.
- Tweaks to the `GitOpsDeploymentManagedEnvironment` API documentation and the corresponding comments in the Go structs.
- I also renamed Stonesoup -> App Studio, since App Studio is the official name for open source upstream project (with RHTAP being the downstream product)

Updates to ManagedEnv API documentation and Go struct comments

---

manifests-v1/database-init/job.yaml
manifests-v1/postgresql-staging/old-bitnami-yaml/values.yaml
manifests-v1/postgresql-staging/postgresql-staging.yaml
manifests/base/postgresql-staging/postgresql-staging.yaml

Revert the changes done to postgres related manifest as part of the PR https://github.com/redhat-appstudio/managed-gitops/pull/418. These changes broke the existing installation in staging environment as the postgresql pods never reached the ready state.
The readiness probe was failing with the following error
```
sh-4.4$ /usr/libexec/check-container      
pg_isready: error: too many command-line arguments (first is "0")
Try "pg_isready --help" for more information.
sh-4.4$ echo $?
3
```

Fixed manifests to use hardcoded DB name instead of postgres database name from env

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
tests-e2e/Makefile
tests-e2e/core/core_suite_test.go
tests-e2e/core/snapshotenvironmentbinding_test.go

- Added labels to GitOpsDeployment resources to identify the associated application, component and environment

Add application/component/environment labels to GitOpsDeployment resources

---

appstudio-controller/config/rbac/role.yaml
appstudio-controller/controllers/appstudio.redhat.com/predicate_provision.go
appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller.go

Fix for `SpaceRequests` related E2E test failure due to missing RBAC policy.
```
Summarizing 1 Failure:
[FAIL] Devsandbox deployment controller tests Testing Devsandbox deployment controller [It] should create a DeploymentTarget for a SpaceRequest with dtc Label
/workspace/git/managed-gitops-git/tests-e2e/core/devsandboxdeployment_test.go:129
```
Error in appstudio-controller logs:
```
2023-04-22T16:55:29.721603669Z	ERROR	failed to create the DeploymentTarget for a SpaceRequest	
{
"controller": "spacerequest", 
"controllerGroup": "toolchain.dev.openshift.com", 
"controllerKind": "SpaceRequest", 
"spaceRequest": {
"name":"test-spacerequest","namespace":"gitops-service-e2e"
}, 
"namespace": "gitops-service-e2e", "name": "test-spacerequest",
"reconcileID": …
```

fix(STONEINTG-261): missing permission to update finalizers

---

manifests/base/gitops-service-argocd/base/argo-cd.yaml

The only way this will work is if we move to the latest channel at this time, OR, the 1.8 release is promoted to the stable channel.  See screenshots in jira.
See https://issues.redhat.com/browse/GITOPSRVCE-150

Malicious Git repositories as input to GitOpsDeployment (#150)

---

backend/eventloop/application_event_loop/application_event_runner.go

* Use a common context for all events in the application event runner. Creating a new context for every event will cause it to stay on the heap until it is canceled.
* Increase maximum backoff retry duration so the controller doesn't reconcile too much on CRs with errors.
The memory increased by almost 200MiB in the course of  2 hours.
We can observe that memory has been almost the same in the 2 hours window with the same load.
https://issues.redhat.com/browse/GITOPSRVCE-557

Fix gradual memory leak in the backend controller

---

cluster-agent/utils/argocd_create.go
manifests/base/gitops-service-argocd/base/argo-cd.yaml

- Set the refresh rate by configuring the `ARGOCD_RECONCILIATION_TIMEOUT` environment variable in the application controller and repo server
1. Create a sample GitOpsDeployment and check if the corresponding Argo CD app is synced.
2. Check the log timestamp of the application controller pod in the `gitops-service-argocd` namespace and verify if Argo CD refreshes the app every 60s.
https://issues.redhat.com/browse/GITOPSRVCE-425

Set Argo CD reconciliation timeout env variable

---

tests-e2e/core/promotionrun_controller_test.go
tests-e2e/fixture/fixture.go

- Run PromotionRun E2E test apps in separate namespaces so that the two apps don't share resources, which leads to syncing issues with Argo CD.
- This requires a new version of the e2e apps, since otherwise the two instances of the application will try to create a route with the same name, which is not allowed by OpenShift. The route-less version of the apps was committed via https://github.com/redhat-appstudio/managed-gitops/pull/435

Run PromotionRun E2E test apps in separate namespaces

---

Makefile
appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
appstudio-controller/go.mod
appstudio-controller/go.sum
manifests/base/crd/overlays/local-dev/kustomization.yaml
tests-e2e/core/managed_environment_test.go
tests-e2e/fixture/managedenvironment/fixture.go
tests-e2e/go.mod
tests-e2e/go.sum
tests-e2e/main.go

- Added namespaces and clusterResources fields to the app studio Environment API
- Updated the appstudio controller to copy these fields from the app studio Environment when a GitOpsDeploymentManagedEnvironment is created

Add namespaces and clusterResources fields to the app studio Environment API

---

tests-e2e/core/snapshotenvironmentbinding_test.go
tests-e2e/fixture/binding/fixture.go

- This PR fixes this race condition in SEB tests:
```
Summarizing 1 Failure:
[FAIL] SnapshotEnvironmentBinding Reconciler E2E tests Testing SnapshotEnvironmentBinding Reconciler. [It] Should recreate GitOpsDeployment, if Binding still exists but GitOpsDeployment is deleted.
/home/jgw/managed-gitops/managed-gitops/tests-e2e/core/snapshotenvironmentbinding_test.go:370
```
The race condition was due to the fixture function comparing the sync status/health/commit id, which the test was not designed to expect.

Fix comparison race condition in SnapshotEnvironmentBinding E2E tests

---

backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go

- The backend controller should not forget to remove the finalizer from a deleted GitOpsDepl when the controllers are restarted. Currently, we skip handling the deletion if the DB resources are already removed even though the GitOpsDeployment with a finalizer could still exist.
https://issues.redhat.com/browse/GITOPSRVCE-455

fix: remove finalizer for a deleted GitOpsDepl when the controllers are restarted

---

utilities/upgrade-service/README.md
utilities/upgrade-service/install-upgrade.sh

- During upgrade, the terminating pod would also be in the list of pods to validate the success of an upgrade and the upgrade would always fail due to the terminated pod.
- Better printing of help message

Add pod status check and update help message

---

backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go

- Added new message for when the check for cluster access returns status of `forbidden`.
- Added new unit tests for this situation.

Improve error message when ServiceAccount doesn't have needed roles

---

backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go

- Updated the error message produces when the user in the kubeconfig doesn't have a token
- Added a unit test to validate the error message

Update error message to indicate that kubeconfig must have a token

---

backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
tests-e2e/argocd/argocd_application_test.go
tests-e2e/argocd/queryscoped_cluster_secrets_test.go

- Two of the e2e tests in the argocd package don't call EnsureCleanSlate() before running, which makes them sucseptable to failing if a prior test leave some conflicting artifacts around.

Change argocd e2e tests to call EnsureCleanSlate() before running

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
tests-e2e/appstudio/snapshotenvironmentbinding_test.go
tests-e2e/fixture/gitopsdeployment/fixture.go

- Updated the SnapshotEnvironmentBinding reconciler to delete any GitOpsDeployments that are not associated with a Component.
- Added unit and e2e tests for the deletion of deployments in response to removal of components
- Added constant strings for the keys used for the labels applied to the deployment to identify the associated application, component and environment
The most efficient way to find the deployments to delete uses the `component` label on the deployment as the key to a map of expected deployments.  Label values are limited in length to 63 characters (in the production, the names of components, applications and environments will be limited to 63 characters by a webhook.) The existing code that sets the labels on the deployment truncates the value if the limit is exceeded. …

Delete GitOpsDeployment when Component removed from SEB

---

.tekton/push.yaml

- Pushes to the `main` branch should not update the infra-deployments repo: instead we should only rely on pushes to the `release-summit-2023` branch to update the infra-deployments repo
- This will be re-enabled once summit is over (and the summit PipelineRun and branch will be removed).

Temporarily disable infra-deployments repo update

---

backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/eventlooptypes/types.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
cluster-agent/controllers/argoproj.io/namespace_reconciler.go
cluster-agent/controllers/managed-gitops/operation_controller.go
cluster-agent/metrics/argocd/argocd_metrics.go

This PR deals with all the places in the code where it was assumed that only a single Argo CD instance (a single GitOpsEngineInstance) exists. Changing that to fetch the ArgoCD namespace from GitopsEngineInstance database row's value i.e. `Namespace_name`. The unit tests and e2e-tests aren't updated if it is not a reference but instead a hardcoded value.
https://issues.redhat.com/browse/GITOPSRVCE-421

Update code to remove a single 'gitops-service-argocd' Argo CD namespace

---

Makefile
cluster-agent/Makefile

Remove references to Kubeconfig in makefiles as it is no longer required (was previously used for KCP support) and is causing an error (cluster agent) in CI. 
https://issues.redhat.com/browse/GITOPSRVCE-453

Remove references to KUBECONFIG

---

manifests/overlays/appstudio-staging-cluster/kustomization.yaml

- The `DeploymentTargetClass` is not needed to be defined when running the appstudio-e2e tests, as part of the infra-deployments repository.

Remove DTClass from appstudio-e2e tests overlay

---

Makefile
Procfile.no-self-heal
backend-shared/util/util.go
backend-shared/util/util_test.go
backend/Makefile
backend/eventloop/db_reconciler.go
cluster-agent/Makefile
cluster-agent/controllers/argoproj.io/namespace_reconciler.go
manifests/overlays/k8s-env-e2e/backend-deployment-patch.yaml
manifests/overlays/k8s-env-e2e/cluster-agent-deployment-patch.yaml
manifests/overlays/k8s-env-e2e/kustomization.yaml
scripts/openshiftci-presubmit-e2e-tests.sh

- Added ability to use an environment variable to set the the interval in minutes for both database and namespace reconciliation.  If the variable is set to `0`, reconciliation will be disabled.  If the variable is not set, the current value of `30` minutes will be used
- Updated the Makefiles for the backend and the cluster-agent to set the variable to `0` to disable reconciliation when running the e2e and chaos tests.

Add ability to control the frequency of self-healing

---

appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller_test.go
appstudio-controller/main.go
backend-shared/util/time.go

- Remove the `time.Sleep()` used in the deploymenttargetreclaimer_controller.go and replace it with mocked time. 
https://issues.redhat.com/browse/GITOPSRVCE-576

Remove time.Sleep() and replace it with mocked time

---

backend/eventloop/application_event_loop/application_event_runner_syncruns.go
backend/eventloop/application_event_loop/application_event_runner_syncruns_test.go
backend/eventloop/db_reconciler.go
backend/eventloop/db_reconciler_test.go

- The Application row could have been deleted while processing SyncRun so log and return if the ApplicationID of SyncOperation is empty.
https://issues.redhat.com/browse/GITOPSRVCE-543

Log and return if the ApplicationID of the SyncOperation is not found

---

appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
tests-e2e/core/managed_environment_test.go

- Deleting GitOpsDeploymentManagedEnvironment in environment_controller.go when Environment Resource doesn't exists
- Updated unit test as above
https://issues.redhat.com/browse/GITOPSRVCE-562

Delete GitOpsDeploymentManagedEnvironment when the corresponding Environment resource is deleted

---

appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller_test.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
appstudio-controller/controllers/appstudio.redhat.com/predicates.go
appstudio-controller/controllers/appstudio.redhat.com/predicates_test.go
appstudio-controller/controllers/appstudio.redhat.com/sandboxprovisioner_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
backend-shared/util/log/log.go
tests-e2e/appstudio/devsandboxdeployment_test.go
tests-e2e/appstudio/dt_dtc_dtclass_test.go
tests-e2e/appstudio/sandboxprovisioner_test.go
tests-e2e/appstudio/snapshotenvironmentbinding_test.go
tests-e2e/core/managed_environment_status_test.go
tests-e2e/core/managed_environment_test.go
tests-e2e/fixture/fixture.go
tests-e2e/fixture/gitopsdeployment/fixture.go
tests-e2e/fixture/k8s/fixture.go

- This PR fixes issues reported on [RHTAP-411](https://issues.redhat.com//browse/RHTAP-411):
- 1) The `GitOpsDeploymentManagedEnvironment` was missing a namespace, when it was based on a DTC that had a namespace value
- 2) The `GitOpsDeployment` was missing a namespace, when it came from a `SnapshotEnvironmentBinding` that referenced an `Environment` that referenced a DTC that had a target namespace :grin: (that's a long sentence)
- Plus a bunch of unit and E2E tests, because we should have caught the above previously (we, including myself, just never thought of it at the time)
- And some minor typos/refactoring (I've marked these with GitHub comments).

Ensure DeploymentTarget/SpaceRequest Namespaces are used in GitOpsDeployments destination field

---

.codecov.yml

- I happened to be looking at the [application-service](https://github.com/redhat-appstudio/application-service) repo, and notice they were using a [codecov.yaml file](https://github.com/redhat-appstudio/application-service/blob/main/codecov.yml) to exclude certain classes of files from code coverage.
- They are excluding mocks and generated code, so we can/should do the same.

Ignore mocks and generated files in codecov.yml

---

manifests/base/monitoring/grafana-dashboards-new/gitops-argocd-dashboard.json
manifests/base/monitoring/grafana-dashboards-new/gitops-dashboard.json
manifests/base/monitoring/grafana-dashboards-new/kustomization.yaml

- Remove datasource fields from Grafana dashboard, as Grafana will just use the main data source if one exists (this was recommended by the RHTAP monitoring team)

Remove datasources from Grafana dashboards

---

manifests/base/monitoring/grafana-dashboards-new/kustomization.yaml

- Remove `disableNameSuffixHash`, as recommended as a solution to the lack of dashboard refresh that was mentioned on https://github.com/redhat-appstudio/application-service/pull/318/files

Remove generatorOptions as it prevents dashboard refresh in RHTAP

---

appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller_test.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller_test.go
tests-e2e/appstudio/dt_dtc_dtclass_test.go

- When the DTC is deleted with a reclaim policy of Retain, we don't remove the matching DT. So the DT might end up pointing to a DTC that doesn't exist. This PR unsets the DT claimRef whenever a DTC is deleted with Retain policy.
Ref: https://redhat-internal.slack.com/archives/C02C3SE8QS2/p1686889611653789?thread_ts=1686730438.404799&cid=C02C3SE8QS2

Unset DT claimRef when the reclaim policy is Retain

---

tests-e2e/argocd/argocd_appproject_test.go
tests-e2e/fixture/application/fixture.go

- Added four new e2e tests to ensure that Argo CD behaves as expected when the repo url specified in an Application matches or doesn't match the url specified in the AppProject to which the Application belongs.

Create an E2E test to verify AppProject behaviour which we rely on

---

backend-shared/util/log/log.go

- At present, it looks like we're only detecting pointers to Secrets as Secrets in the `LogAPIResourceChangeEvent` code. We should instead check for both pointers and struct objects.

Don't log the contents of non-pointer Secret objects

---

manifests/base/gitops-service-argocd/base/argo-cd-application-controller-clusterrole.yaml
manifests/base/gitops-service-argocd/base/argo-cd-application-controller-clusterrolebinding.yaml
manifests/base/gitops-service-argocd/base/argo-cd-server-clusterrole.yaml
manifests/base/gitops-service-argocd/base/argo-cd-server-clusterrolebinding.yaml

- Fix any issue where the names of the clusterrole/rolebindings defined for gitops-service-argocd are conflicting with those used by openshift-gitops on infra-deployments.

Rename ClusterRole/Bindings to prevent name clash with infra-deployments

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeployment_webhook.go
backend-shared/apis/managed-gitops/v1alpha1/gitopsdeployment_webhook_test.go
backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentmanagedenvironment_webhook.go
backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentmanagedenvironment_webhook_test.go
backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentrepositorycredential_webhook.go
backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentrepositorycredential_webhook_test.go
backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentsyncrun_webhook.go
backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentsyncrun_webhook_test.go
tests-e2e/appstudio/webhook_test.go
tests-e2e/core/environment_test.go
tests-e2e/core/gitopsdeployment_syncrun_test.go
tests-e2e/core/gitopsdeployment_test.go
tests-e2e/core/managed_environment_test.go

- Added validation for empty Environment and non-empty Namespace
- Unit/e2e tests
- Moved error strings to constants
https://issues.redhat.com/browse/GITOPSRVCE-642

Add webhook validation to avoid creation of GitopsDeployment for empty Environment field and non-empty namespace 

---

appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller.go
appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller_test.go
tests-e2e/appstudio/deploymenttargetclaim_binder_test.go
tests-e2e/appstudio/dt_dtc_dtclass_test.go
tests-e2e/fixture/fixture.go
tests-e2e/fixture/k8s/fixture.go

- Updated DeploymentTarget Reconciler so that it will ensure the finalizer is ALWAYS added to the DeploymentTarget.
- Updated unit/e2e tests to verify the finalizer is set
- Wrote a quick unit test for findDeploymentTargetsForSpaceRequests

DeploymentTarget reconciler should add the DT finalizer in all cases

---

backend-shared/util/fauxargocd/faux_argo_cd.go

In the namespace_reconciler, the Name and Namespace fields of the application that we are searching for are blank and so when the reconciler tries to get the application resource, it obviously cannot find it, and so it tries to create the operation, etc. every 30 minutes.
Why is the name and namespace empty?  
namespacedName := types.NamespacedName{
Name:      applicationFromDB.Name,
Namespace: applicationFromDB.Namespace}
The unmarshalling step actually was the issue.  It should actually have failed and errored out, if we had used UnmarshalStrict instaed here:
// Fetch the Application object from DB
if err := yaml.Unmarshal([]byte(applicationRowFromDB.Spec_field), &applicationFromDB); err != nil {
and it would have indicated that the two fields are undefined after unmarshaling. The fix …

Unnecessary Operations CRs/DBs are being created/cleaned (#659)

---

appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetbinder_controller.go
backend/eventloop/application_event_loop/application_event_loop.go
backend/eventloop/application_event_loop/application_event_loop_test.go

- Move the contents of `applicationEventQueueLoop` into a separate struct, so that the state can be verified by unit tests
- Move the existing logic (which processesindividual application event messages) into a new function `processApplicationEventQueueLoopMessage`
- Call `processApplicationEventQueueLoopMessage` via new unit tests
-

Refactor applicationEventQueueLoop so it can be unit tested, and write new unit tests for it

---

.codecov.yml

- Update .codecov.yml to block PRs from merging if they regress coverage by more than 0.2%

Set codecov to block PRs if they decrease coverage

---

backend-shared/util/log/log.go

- Changed the logger created within LogAPIResourceChangeEvent to use the location of the caller instead of the location within LogAPIResourceChangeEvent itself.

Use WithCallDepth in LogAPIResourceChangeEvent

---

Dockerfile
Dockerfile.ci

- Explicitly specify the image to use in FROM statement in the Dockerfiles. Dependabot doesn't seem to handle specifying the image via an ARG.

Don't use variable to specify FROM image in Dockerfiles

---

manifests/overlays/appstudio-staging-cluster/appstudio-controller-deployment-patch.yaml

- When running on dev/test K8s environment, where the K8s API URL is potentially self-signed, we need to tell the DeploymentTarget provisioner to allow self-signed certifcates.

Allow self-signed certificates in DT provisioner, on dev/test envs

---

backend-shared/db/app_project_repository.go
backend-shared/db/app_project_repository_test.go
backend-shared/db/db_field_constants.go
backend-shared/db/queries.go
backend-shared/db/test_utils.go
backend-shared/db/types.go
backend-shared/db/unreliable_db_client.go
backend/Makefile
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/db_reconciler_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential.go
backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
db-schema.sql
docs/sandboxing-via-appprojects.md
tests-e2e/Makefile
tests-e2e/core/gitopsdeployment_test.go
tests-e2e/fixture/fixture.go
utilities/db-migration/migration_test/add_test_values/add_db_values.go
utilities/db-migration/migrations/000019_v19.down.sql
utilities/db-migration/migrations/000019_v19.up.sql

- The logic for determining what `AppProjectRepository` rows should exist in the database is now entirely within the `reconcileAppProjectRepositories` function of the shared resource loop
- This avoids a potential race condition where multiple GitOpsDeployments/RepositoryCredentials were reconciling AppProjects at the same time.
- To be clear: this race condition was due to a flaw in *my* proposal in the original design document, and not an issue with the implementation itself by the GitOps Service EE team.
- The existing AppProjectRepository reconcile functions now call the shared resource loop function

Fix race condition in AppProjectRepository reconciliation and remove RepositoryCredential field

---

backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go

- Improve the test coverage of 'internalProcessMessage_internalReconcileSharedManagedEnv', 'createNewClusterCredentials', 'locateContextThatMatchesAPIURL', in backend component.

Improve test coverage of backend pt1

---

.ci/base-image/Dockerfile

- As part of updating our Argo CD dependency to 2.7.11, we had to update to use golang 1.19.  The .ci/base-image/Dockerfile should be updated as well.

Update .ci base-image Dockerfile go version

---

backend/eventloop/workspace_resource_event_loop.go
backend/eventloop/workspace_resource_event_loop_test.go

- `isManagedEnvironmentConnectionUserError` is panic-ing when the error is nil, so check for that case
- Unit test that verifies that case

Fix panic in isManagedEnvironmentConnectionUserError

---

appstudio-controller/controllers/appstudio.redhat.com/deploymenttargetreclaimer_controller.go
tests-e2e/appstudio/deploymenttargetclaim_binder_test.go

- The DeploymentTarget reclaimer will unset the claimRef if the specified DTC is not found. In the e2e test, we were creating a fake DT pointing to a DTC which didn't exist and the claimRef field was unset by the reclaimer controller. Hence the binding controller had two matching DTs(the correct DT and the fake DT whose claimRef was unset) available for a single DTC. So, when the binding controller picked the fake DT it resulted in an intermittent failure.
- In order to solve this we create a DTC that binds with the fake DT so that its claimRef field will not be unset.
https://issues.redhat.com/browse/GITOPSRVCE-711

Fix intermittent binding controller e2e test

---

cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache_suite_test.go
cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache_test.go

Looks like the existing tests are not run, and the existing tests fail.  Enabling the first one will test the DeleteApplicationStateById function and its related process* function. See code coverage report.
https://issues.redhat.com/browse/GITOPSRVCE-701

Tests for application_info_cache.go in cluster-agent component (#701)

---

backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential.go
backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
tests-e2e/core/gitopsdeployment_test.go
tests-e2e/fixture/fixture.go

- See parent item for description of the bug
- Updated the GitOpsDeployment/RepositoryCredential reconcilers (runners) to ensure they create an Operation whenever AppProjectRepository is updated
- Adds unit/E2E tests to verify the discovered bug

GITOPSRVCE-742: ensure operation is always created when appproject DB is updated

---

backend-shared/db/util/utils.go
backend/eventloop/cluster_reconciler.go

- On RHTAP clusters, the 'failed to list resources' from `cluster_reconciler.go` is logging at error level, rather than at debug level, due to the use of Error function.

Fix 'failed to list resources' debug statement logging at error level

---

backend/eventloop/workspace_event_loop.go

Unit test are currently failing here:
```
• [PANICKED] [0.000 seconds]
Workspace Event Loop Test processWorkspaceEventLoopMessage tests shouldn't forward the event if it is completed/nil/unknown [It] reject the event if it is nil
/home/runner/work/managed-gitops/managed-gitops/backend/eventloop/workspace_event_loop_test.go:671
Timeline >>
STEP: verify that the event is not forwarded @ 09/11/23 11:19:17.316
[PANICKED] in [It] - /opt/hostedtoolcache/go/1.19.12/x64/src/runtime/panic.go:260 @ 09/11/23 11:19:17.317
<< Timeline
[PANICKED] Test Panicked
In [It] at: /opt/hostedtoolcache/go/1.19.12/x64/src/runtime/panic.go:260 @ 09/11/23 11:19:17.317
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace
github.com/redhat-appstudio/managed-gitops/backend/eventloop.handleW …
```

Move sanity test before the log statement to avoid panic in 'workspace_event_loop_test' unit tests

---

backend/config/manager/manager.yaml
cluster-agent/config/manager/manager.yaml
tests-e2e/Makefile

- Now that we've squashed the bugs, let's finally enable the AppProject isolation feature flag

GITOPSRVCE-56: Enable AppProject isolation feature flag via environment variable

---

tests-e2e/Makefile

- E2E tests were broken by this invalid whitespace (spaces, rather than tab) on tests-e2e/Makefile, this reverts the whitespace change.

Fix invalid whitespace on tests-e2e/Makefile

---

backend/eventloop/repocred_reconciler_test.go

- Add unit tests for 'reconcileRepositoryCredentialStatus' in the backend component.

Improve test coverage of backend pt2

---

cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go

This PR is to cover deleteArgoCDApplicationOfDeletedApplicationRow function, of Cluster-agent component.
https://issues.redhat.com/browse/GITOPSRVCE-703

chore: improve test coverage.

---

manifests/base/gitops-service-argocd/base/argo-cd.yaml

- Limit the number of parallel `git clone`/`kustomize` calls that can be running at any given time, so as to avoid OOM
- Limit `git clone`/`kustomize` calls to 30 seconds
- Raise the memory limit as we are close in some scenarios

Restrict repo server parallelism and git/kustomize run time

---

backend/eventloop/workspace_resource_event_loop.go
backend/eventloop/workspace_resource_event_loop_test.go

- Refactor the larger workspace resource loop handler into smaller functions
- Add unit tests 
https://issues.redhat.com/browse/GITOPSRVCE-697

Improve test coverage of workspace_resource_event_loop.go

---

backend/Makefile
cluster-agent/Makefile

- A change was made recently (PR #643) to enable AppProject isolation for `make test-e2e`.  But it was not enabled for the run targets in the various Makefiles, so running locally using `make start-e2e` would cause some of the tests to fail

Enable AppProject isolation for Makefile run targets

---

appstudio-controller/config/webhook/manifests.yaml

- As reported on Slack, there are certificate issues with the Environment webhook, which are occuring for no obvious reason :stuck_out_tongue: , so I am once again temporarily disabling this webhook.

Disable Environment webhook

---

.github/workflows/static.yml
backend-shared/db/applicationstates.go
backend-shared/db/applicationstates_test.go
backend-shared/db/db_field_constants.go
backend-shared/db/guardrow_test.go
backend-shared/db/types.go
backend-shared/db/util/utils_test.go
backend-shared/util/fauxargocd/faux_argo_cd.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/db_reconciler_test.go
cluster-agent/controllers/argoproj.io/application_controller.go
cluster-agent/controllers/argoproj.io/application_controller_test.go
cluster-agent/controllers/argoproj.io/application_info_cache/application_info_cache_test.go
db-schema.sql
utilities/db-migration/migration_test/add_test_values/add_db_values.go
utilities/db-migration/migration_test/verify_test_values/verify_db_values_test.go
utilities/db-migration/migrations/000020_v20.down.sql
utilities/db-migration/migrations/000020_v20.up.sql

- Introduce a single status field in the ApplicationState DB
- Remove the individual status fields from the ApplicationState DB
- Update the backend and cluster agent to process the single status field
https://issues.redhat.com/browse/GITOPSRVCE-738

Store the full contents of Application status in a single DB field

---

cluster-agent/controllers/argoproj.io/namespace_reconciler.go
cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go

This PR is to add a logic to recreate Secrets in Argo CD namespace if they are required by ManagedEnvironments but missing in Cluster for some reason.
https://issues.redhat.com/browse/GITOPSRVCE-739

Recreate missing Secrets for ManagedEnvironments.

---

backend-shared/util/operations/types.go
backend-shared/util/operations/types_test.go

- This PR does not add the unit tests for service_account.go since it is separate
- The first test tests directly the two functions waitForOperationToComplete and isOperationComplete 
- CreateOperation is not tested thoroughly as well, in particular, there is no test that sets true for waitForOperation. 
- This PR makes some slight tweaks in product code to accommodate this.
- The second tests tests the 'old' CreateOperation via the new doCreateOperation.  I added two operations but only one is probably sufficient.  Let me know if you want to remove one of them
https://issues.redhat.com/browse/GITOPSRVCE-688

Unit tests for waitForOperationToComplete, isOperationComplete (#688)

---

tests-e2e/appstudio/dt_dtc_dtclass_test.go

- Fixed failing of e2e test by adding time interval in Eventually block

Fix failing of DT e2e test

---

backend/eventloop/workspace_resource_event_loop_test.go

- Intermittent, a different a error string is returned, due to where the context cancelled is recognized. 
- This PR updates the error string to handle both cases.

GITOPSRVCE-767: fix interimittent failure in workspace_resource_event_loop_test.go

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go

- I happened to notice that on RHTAP cluster we were making way too many status updates to `SnapshotEnvironmentBinding` CR, despite no obvious changes. 
- This code change should help reduce that, by only updating the status when it has changed, and using a more deterministic generation algorithm that does not rely on Go map key ordering
- Only call `k8sClient.Update` to update the `SnapshotEnvironmentBinding` status IF the contents of the .status field actually changed (otherwise skip)
- Process the component names in alphabetical order, so that the generated status is consistent (deterministic) from run to run
- Misc tweaks:
- Tweak the pointer usage on `SnapshotEnvironmentBinding`
- `Can not` -> `Cannot`

Only call k8s client to update SnapshotEnvironmentBinding status when .status field has changed

---

appstudio-controller/config/webhook/manifests.yaml

- Re-enable environment webhook after it was previously disabled, see 771 for details.

GITOPSRVCE-771: re-enable environment webhook

---

.github/workflows/static.yml
Makefile
backend-shared/Makefile
backend-shared/db/postgres-integration.go
backend/Makefile
cluster-agent/Makefile
manifests/overlays/appstudio-staging-cluster/backend-deployment-patch.yaml
manifests/overlays/appstudio-staging-cluster/cluster-agent-deployment-patch.yaml
manifests/overlays/k8s-env-e2e/cluster-agent-deployment-patch.yaml
manifests/overlays/k8s-env/backend-deployment-patch.yaml
manifests/overlays/k8s-env/cluster-agent-deployment-patch.yaml
manifests/overlays/k8s-env/kustomization.yaml
tests-e2e/Makefile

- Update database connection code to require tls unless the DEV_ONLY_ALLOW_NON_TLS_CONNECTION_TO_POSTGRESQL environment variable is set.

GitOps Service should require TLS for postgresql

---

backend-shared/db/clusteraccess_test.go
backend-shared/db/clustercredentials.go
backend-shared/db/gitopsenginecluster_test.go
backend-shared/db/gitopsengineinstance_test.go
backend-shared/db/guardrow_test.go
backend-shared/db/injection_test.go
backend-shared/db/managedenvironment_test.go
backend-shared/db/test_utils.go
backend-shared/db/types_test.go
backend-shared/db/util/utils.go
backend-shared/db/util/utils_test.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/db_reconciler_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
cluster-agent/controllers/argoproj.io/application_controller_test.go
cluster-agent/controllers/argoproj.io/namespace_reconciler.go
cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go
cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop_test.go
utilities/db-migration/migration_test/add_test_values/add_db_values.go

- At present, in cluster-agent's namespace_reconciler.go, in recreateClusterSecrets, we are iterating through the list of ManagedEnvironments looking for those that do not have a corresponding Argo CD Cluster Secret.
- However, there exist many ManagedEnvironment rows that do not require a cluster secret: any managed environment that corresponds to a '*_tenant' Namespace on the cluster does not require an Argo CD cluster secret. Why? Because Argo CD by default already has the credentials needed to read/write from any namespace on the that it is deployed to.
- We can thus update logic in 'recreateClusterSecrets' to avoid creating Operations for ManagedEnvironments/Applications that target the same cluster as Argo CD.
This PR:
- moves `"serviceaccount_bearer_token"` to a string constant
- …

GITOPSRVCE-778: only create operations for missing external cluster secrets

---

tests-e2e/fixture/appproject/fixture.go

- Based on the failure logs, the error appears to be that the order is different between the expect and actual values
- So just compare in any order

GITOPSRVCE-772: fix intermittent E2E test failure in gitopsdeployment_test.go

---

backend/eventloop/application_event_loop/application_event_loop.go
backend/eventloop/application_event_loop/application_event_loop_test.go
backend/eventloop/application_event_loop/application_event_runner.go
backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/application_event_loop/application_event_runner_test.go
backend/eventloop/application_event_loop/metrics_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go

- Vast majority of new work in this PR is in 'Generic Application Event Loop Runner tests' in `application_event_runner_test.go`
- The rest of the PR is just some misc refactoring:
- In a couple cases, I changed `chan *eventlooptypes.EventLoopEvent` to `chan eventlooptypes.EventLoopEvent`, as it didn't make sense for these to be pointers.
- Added context and factory parameters to ApplicationEventLoopRunner interface

GITOPSRVCE-704: Improve test coverage of 'application_event_runner.go' in backend component

---

backend-shared/db/postgres-integration.go

When I merged GITOSRVCE-731 to staging, I got this error, so this PR should address that:
```
{
"level": "error",
"ts": "2023-10-17T09:26:46.991188015Z",
"caller": "util/util.go:117",
"msg": "NewProductionPostgresDBQueries: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config, unable to connect to database: Host:'multi-tenant-staging-gitopsvc.cksigd96yuso.us-east-1.rds.amazonaws.com:5432' User:'postgres' DB:'postgres' ",
"error": "tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config, unable to connect to database: Host:'multi-tenant-staging-gitopsvc.cksigd96yuso.us-east-1.rds.amazonaws.com:5432' User:'postgres' DB:'postgres' ",
"stacktrace": "github.com/redhat-appstudio/managed-gitops/backend-shared/util.RunTaskUntilTrue\n …
```

GITOPSRVCE-731: add server name to DB TLS conn info

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
tests-e2e/appstudio/promotionrun_controller_seb_test.go
tests-e2e/appstudio/promotionrun_controller_test.go
tests-e2e/appstudio/snapshotenvironmentbinding_test.go
tests-e2e/appstudio/webhook_test.go

- Delete the SnapshotEnvironmentBinding when the associated application is deleted.  Add unit and e2e tests for this.  Update existing tests which used to set the .spec.application field in the SEB without creating an application.

Delete SEB when associated Application is deleted

---

manifests/base/postgresql-staging/postgresql-staging.yaml

- Postgresql dev container should not run as root, and should use a readonly FS

GITOPSRVCE-723: Better secure dev postgresql instance

---

backend/eventloop/application_event_loop/application_event_loop.go
backend/eventloop/eventlooptypes/types.go
backend/eventloop/eventlooptypes/types_test.go
cluster-agent/controllers/managed-gitops/operation_controller.go

- As part of [GITOPSRVCE-704](https://issues.redhat.com//browse/GITOPSRVCE-704) I converted some pointer fields to objects, however there were a couple SEVERE error logs that were checking the pointer.
- Fix invalid SEVERE log entry by only checking field (rather than pointer) of event.Message.Event in app event loop

Fix invalid SEVERE log entry by only checking field (rather than pointer) of event.Message.Event in app event loop

---

backend/eventloop/application_event_loop/application_event_loop.go

- Log statement keys on https://github.com/redhat-appstudio/managed-gitops/pull/690/files were incorrectly paired

Fix log keys in application_event_loop.go

---

cluster-agent/controllers/argoproj.io/namespace_reconciler.go
cluster-agent/controllers/argoproj.io/namespace_reconciler_test.go

This PR is to add a logic to recreate Secrets in Argo CD namespace if they are required by RepositoryCredentials but missing in Cluster for some reason.
https://issues.redhat.com/browse/GITOPSRVCE-740
1. Refactored existing `recreateClusterSecrets_ManagedEnvironments` function.
2. Created a new function `recreateClusterSecrets` which calls `recreateClusterSecrets_ManagedEnvironments` function for creating missing secret for ManagedEnvironments and `recreateClusterSecrets_RepositoryCredentials` for RepositoryCredentials.

Recreate missing Secrets for RepositoryCredentials.

---

appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller.go
appstudio-controller/controllers/appstudio.redhat.com/promotionrun_controller_test.go

- As discussed on Slack (see link in JIRA), when we reference a Component CR, we should use the `.metadata.Name` of the component, rather than the `.spec.ComponentName`

GITOPSRVCE-783: use Component CR .metadata.Name, not ComponentName

---

Dockerfile
backend-shared/db/postgres-integration.go

- Automatically acquire the latest Amazon CA root certs, and add them to the system store within the container
- Re-enable TLS verification, to valid RDS instances using those certificates

GITOPSRVCE-731: Add Amazon CA root certs, re-enable TLS verification

---

appstudio-controller/config/default-no-prometheus/kustomization.yaml
appstudio-controller/config/default-no-prometheus/webhookcainjection_patch.yaml
appstudio-controller/config/default/kustomization.yaml
appstudio-controller/config/webhook/manifests.yaml
appstudio-controller/controllers/webhooks/environment_webhook.go
appstudio-controller/controllers/webhooks/environment_webhook_unit_test.go
appstudio-controller/controllers/webhooks/promotionrun_webhook.go
appstudio-controller/controllers/webhooks/promotionrun_webhook_test.go
appstudio-controller/controllers/webhooks/snapshot_webhook unit_test.go
appstudio-controller/controllers/webhooks/snapshot_webhook.go
appstudio-controller/controllers/webhooks/snapshotenvironmentbinding_webhook.go
appstudio-controller/controllers/webhooks/snapshotenvironmentbinding_webhook_test.go
appstudio-controller/controllers/webhooks/webhooks.go
appstudio-controller/go.mod
appstudio-controller/go.sum
appstudio-controller/main.go
tests-e2e/appstudio/dt_dtc_dtclass_test.go
tests-e2e/appstudio/environment_test.go
tests-e2e/appstudio/promotionrun_controller_test.go
tests-e2e/appstudio/snapshotenvironmentbinding_test.go
tests-e2e/appstudio/webhook_test.go
tests-e2e/go.mod
tests-e2e/go.sum
utilities/load-test/go.mod
utilities/load-test/go.sum

This PR is to move GitOps Service related webhooks to managed-gitops repo from application.
[An application-api PR](https://github.com/redhat-appstudio/application-api/pull/76) was merged which removed GitOps-Service related webhooks from there and in this PR all those webhooks are added with few modifications.
https://issues.redhat.com/browse/GITOPSRVCE-762

Move webhooks to GitOps-Service.

---

appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller.go
appstudio-controller/controllers/appstudio.redhat.com/snapshotenvironmentbinding_controller_test.go
tests-e2e/appstudio/snapshotenvironmentbinding_test.go

There is a theoretical race condition (not seen in practice, to my knowledge) where a SnapshotEnvironmentBinding (SEB) is reconciled before the Application exists, which causes the SEB to be deleted by our orphaned SEB detection login.
For example:
1) SEB is created
2) SEB is reconciled. SEB `Reconcile()` logic detects that the parent Application doesn't exist, and thus the Reconcile logic will automatically delete the SEB.
3) Application is created.
You could imagine a case like this might happen if you were kubectl apply-ing a bunch of resources at once, and the SnapshotEnvironmentBinding was reconciled before the Application was created.
In any case, the fix is just to wait a few minutes (via requeue) before deletion.

GITOPSRVCE-787: wait X minutes before deleting orphaned SEB

---

backend/eventloop/application_event_loop/application_event_runner_deployments.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
backend/eventloop/workspace_resource_event_loop.go

- When a user specifies an invalid value in a `GitOpsDeploymentManagedEnvironment` -- for example, they reference a Secret that doesn't exist -- we don't need to keep re-reconciling that resource.
- In this case, the user should fix the `GitOpsDeploymentManagedEnvironment` -- by adding a proper Secret -- before we reconcile that resource again.
- These types of errors are 'user errors': cases where a user is specifying invalid API input, and there is no reason for us to keep trying to reconcile the resource.
- So, as part of this PR, the `ReconcileSharedManagedEnv` will now detect user errors, and if found, return true.
- Then in the workspace resource event loop, we stop reconciling when a user error is detected.

GITOPSRVCE-776: dont re-reconcile on user errors

---

backend/eventloop/db_reconciler.go
backend/eventloop/db_reconciler_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop_managedenv.go

- Similar to https://github.com/redhat-appstudio/managed-gitops/pull/698, we want to avoid burying errors (not returning an error whenever an error occurs)
- In most case, even after an error occurs, we still want to keep processing the database resources, but, we should still return the _first_ error that occured
- This allows us to verify from the unit tests that no errors are occurring

Refactor backend db reconciler to return first error after processing resources, then verify no errors occur in unit tests

---

scripts/openshiftci-presubmit-e2e-tests.sh

- Added kubectl command in `openshiftci-presubmit-e2e-tests.sh` file
- Command description:
- kubectl get deployments --no-headers -o custom-columns="DEPLOYMENT:.metadata.name : retrieves a list of deployment names in your cluster.
- xargs -I {} : is used to iterate through each deployment name.
- kubectl rollout status deploy/{} - s run for each deployment, where {} is replaced with the deployment name. This checks the rollout status for each deployment.
https://issues.redhat.com/browse/GITOPSRVCE-754

Add kubectl command to check  controller deployments are ready

---

docs/api.md

- We added a couple more status fields to `GitOpsDeployment`, this ensures they are documented within API.md

docs: add ComparisonError and operationState to api.md

---

manifests/base/gitops-service-argocd/base/argo-cd-application-controller-clusterrole.yaml
manifests/base/gitops-service-argocd/base/argo-cd-application-controller-clusterrolebinding.yaml
manifests/base/gitops-service-argocd/base/argo-cd-server-clusterrole.yaml
manifests/base/gitops-service-argocd/base/argo-cd-server-clusterrolebinding.yaml
manifests/scripts/openshift-argo-deploy/openshift-gitops-subscription.yaml
tests-e2e/fixture/fixture.go

- Platform team would like use to avoid using very permissive cluster roles in our `gitops-service-argocd` instance, so the easiest way to do that is to move GitOps Service' Argo CD instance to be strictly namespace-scoped.

GITOPSRVCE-769: Switch to namespace-scoped gitops-service-argocd

---

backend-shared/apis/managed-gitops/v1alpha1/gitopsdeploymentrepositorycredential_types.go
backend-shared/util/util.go
backend/controllers/managed-gitops/gitopsdeploymentmanagedenvironment_controller.go
backend/controllers/managed-gitops/gitopsdeploymentrepositorycredential_controller.go
backend/controllers/managed-gitops/gitopsdeploymentrepositorycredential_controller_test.go
backend/eventloop/db_reconciler_test.go
backend/eventloop/repocred_reconciler.go
backend/eventloop/repocred_reconciler_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop.go
backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential.go
backend/eventloop/shared_resource_loop/sharedresourceloop_repositorycredential_test.go
backend/eventloop/shared_resource_loop/sharedresourceloop_test.go
backend/eventloop/workspace_resource_event_loop.go
backend/eventloop/workspace_resource_event_loop_test.go
tests-e2e/appstudio/environment_test.go
tests-e2e/core/privaterepo_test.go
tests-e2e/core/queryscoped_cluster_secrets_test.go
tests-e2e/fixture/gitopsdeploymentrepositorycredential/fixture.go
tests-e2e/fixture/k8s/fixture.go
tests-e2e/fixture/managedenvironment/fixture.go

- At present, the GitOpsRepositoryCredential reconciler is not watching Secret resources for changes. 
- This means that if a user changes the private Git repository credentials defined in a Secret (for example, changing their password), this will not be detected by the GitOpsRepositoryCredential reconciler.
- The fix is to add a watch for Secret resources to the controller, plus unit/E2E tests to verify
- Other PR Changes:
- Fixed a bug where Operation was created in the Namespace of the GitOpsDeploymentReploymentCredential, rather than in the Argo CD namespace
- Add a new function interface which allow us to mock the validation of Git repos from unit tests
- Fix constant typos
- Improved pointer hygiene
- Change Secret watch type from `predicate.GenerationChangedPredicate` to …

GITOPSRVCE-788: reconcile changes to repository Secrets

---

manifests/base/postgresql-staging/postgresql-staging-secret.yaml

- Remove old, unused Secret value from repo

Remove old, unused Secret value from repo
